(self.AMP=self.AMP||[]).push({n:"amp-ad-network-doubleclick-impl",v:"1527021682973",f:(function(AMP){var h;function aa(a,b){function c(){}c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a;for(var d in b)if(Object.defineProperties){var e=Object.getOwnPropertyDescriptor(b,d);e&&Object.defineProperty(a,d,e)}else a[d]=b[d]}function ba(a,b){b=void 0===b?"":b;try{return decodeURIComponent(a)}catch(c){return b}};var ca=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;function q(a){var b=Object.create(null);if(!a)return b;for(var c;c=ca.exec(a);){var d=ba(c[1],c[1]),e=c[2]?ba(c[2],c[2]):"";b[d]=e}return b};var da="";function r(a){var b=a||self,c;if(b.AMP_MODE)c=b.AMP_MODE;else{c=b;var d=q(c.location.originalHash||c.location.hash),e=q(c.location.search);da||(da=c.AMP_CONFIG&&c.AMP_CONFIG.v?c.AMP_CONFIG.v:"011527021682973");c=b.AMP_MODE={localDev:!1,development:!("1"!=d.development&&!c.AMP_DEV_MODE),examiner:"2"==d.development,filter:d.filter,geoOverride:d["amp-geo"],minified:!0,lite:void 0!=e.amp_lite,test:!1,log:d.log,version:"1527021682973",rtvVersion:da}}return c};var ea=Object.prototype.toString;function w(a){return"[object Object]"===ea.call(a)}function fa(a){return"number"===typeof a&&isFinite(a)};function ga(a){var b=a.message,c=String(Math.random());a.message=c;if(a.message===c)return a.message=b,a;var b=Error(a.message),d;for(d in a)b[d]=a[d];b.stack=a.stack;return b}function ha(a){for(var b=null,c="",d=0;d<arguments.length;d++){var e=arguments[d];e instanceof Error&&!b?b=ga(e):(c&&(c+=" "),c+=e)}b?c&&(b.message=c+": "+b.message):b=Error(c);return b}function x(a){var b=ha.apply(null,arguments);setTimeout(function(){self.reportError(b);throw b;})}self.log=self.log||{user:null,dev:null,userForEmbed:null};
var ia=self.log;function y(){if(!ia.user)throw Error("failed to call initLogConstructor");return ia.user}function z(){if(ia.dev)return ia.dev;throw Error("failed to call initLogConstructor");};var ja=Object.prototype.hasOwnProperty;function ka(){var a,b=Object.create(null);a&&Object.assign(b,a);return b}function A(a){return a||{}}
function la(a,b){var c;c=void 0===c?10:c;var d=[],e=[];e.push({t:a,s:b,d:0});for(b={};0<e.length;){var f=e.shift();b.t=f.t;b.s=f.s;b.d=f.d;if(d.includes(b.s))throw Error("Source object has a circular reference.");d.push(b.s);b.t!==b.s&&(b.d>c?Object.assign(b.t,b.s):(Object.keys(b.s).forEach(function(a){return function(b){var c=a.s[b];if(ja.call(a.t,b)){var d=a.t[b];if(w(c)&&w(d)){e.push({t:d,s:c,d:a.d+1});return}}a.t[b]=c}}(b)),b={s:b.s,t:b.t,d:b.d}))}return a};function ma(a,b){return b.length>a.length?!1:0==a.lastIndexOf(b,0)}function na(a){for(var b=a.length,c=5381,d=0;d<b;d++)c=33*c^a.charCodeAt(d);return String(c>>>0)};var oa=self.AMP_CONFIG||{},pa=oa.thirdPartyUrl||"https://3p.ampproject.net",qa=oa.thirdPartyFrameHost||"ampproject.net";function ra(a){this.ab=a;this.K=Object.create(null)}ra.prototype.get=function(a){if(this.K[a])return this.K[a].access=Date.now(),this.K[a].payload};ra.prototype.put=function(a,b){var c=this;this.K[a]={payload:b,access:Date.now()};var d=Object.keys(this.K);d.length>this.ab&&(z().warn("lru-cache","Trimming template cache"),d.sort(function(a,b){return c.K[b].access-c.K[a].access}),delete this.K[d[d.length-1]])};A({c:!0,v:!0,a:!0,ad:!0});var sa,va,wa=["javascript:","data:","vbscript:"];
function C(a,b){sa||(sa=self.document.createElement("a"),va=self.UrlCache||(self.UrlCache=new ra(100)));var c=va.get(a);if(c)return c;var d=sa;d.href=a;d.protocol||(d.href=d.href);var e={href:d.href,protocol:d.protocol,host:d.host,hostname:d.hostname,port:"0"==d.port?"":d.port,pathname:d.pathname,search:d.search,hash:d.hash,origin:null};"/"!==e.pathname[0]&&(e.pathname="/"+e.pathname);if("http:"==e.protocol&&80==e.port||"https:"==e.protocol&&443==e.port)e.port="",e.host=e.hostname;e.origin=d.origin&&
"null"!=d.origin?d.origin:"data:"!=e.protocol&&e.host?e.protocol+"//"+e.host:e.href;var f=e,g=f;if(b)return g;va.put(a,g);return g}function xa(a,b){var c;if(!b)return a;var d=a.split("#",2),e=d[0].split("?",2),f=e[0]+(e[1]?c?"?"+b+"&"+e[1]:"?"+e[1]+"&"+b:"?"+b);return f+=d[1]?"#"+d[1]:""}
function ya(a){var b=[],c;for(c in a){var d=a[c];if(null!=d)if(Array.isArray(d))for(var e=0;e<d.length;e++){var f=d[e];b.push(encodeURIComponent(c)+"="+encodeURIComponent(f))}else e=d,b.push(encodeURIComponent(c)+"="+encodeURIComponent(e))}return b.join("&")}function F(a){"string"==typeof a&&(a=C(a));var b;(b="https:"==a.protocol||"localhost"==a.hostname)||(a=a.hostname,b=a.length-10,b=0<=b&&a.indexOf(".localhost",b)==b);return b}
function za(a,b){var c;c=void 0===c?"source":c;y().assert(null!=a,"%s %s must be available",b,c);var d=a;y().assert(F(d)||/^(\/\/)/.test(d),'%s %s must start with "https://" or "//" or be relative and served from either https or from localhost. Invalid value: %s',b,c,d)}function Aa(a){if(!a)return!0;"string"==typeof a&&(a=C(a));return!wa.includes(a.protocol)};function Ba(a){return a.AMP_CONFIG&&a.AMP_CONFIG.type?a.AMP_CONFIG.type:"unknown"}function G(a,b){var c=Ca(a);return!!c[b]}
function Ca(a){if(a.__AMP__EXPERIMENT_TOGGLES)return a.__AMP__EXPERIMENT_TOGGLES;a.__AMP__EXPERIMENT_TOGGLES=Object.create(null);var b=a.__AMP__EXPERIMENT_TOGGLES;if(a.AMP_CONFIG)for(var c in a.AMP_CONFIG){var d=a.AMP_CONFIG[c];"number"===typeof d&&0<=d&&1>=d&&(b[c]=Math.random()<d)}if(a.AMP_CONFIG&&Array.isArray(a.AMP_CONFIG["allow-doc-opt-in"])&&0<a.AMP_CONFIG["allow-doc-opt-in"].length){var e=a.AMP_CONFIG["allow-doc-opt-in"],f=a.document.head.querySelector('meta[name="amp-experiments-opt-in"]');
if(f){var g=f.getAttribute("content").split(",");for(c=0;c<g.length;c++)-1!=e.indexOf(g[c])&&(b[g[c]]=!0)}}Object.assign(b,Da(a));if(a.AMP_CONFIG&&Array.isArray(a.AMP_CONFIG["allow-url-opt-in"])&&0<a.AMP_CONFIG["allow-url-opt-in"].length){c=a.AMP_CONFIG["allow-url-opt-in"];a=q(a.location.originalHash||a.location.hash);for(var k=0;k<c.length;k++){var l=a["e-"+c[k]];"1"==l&&(b[c[k]]=!0);"0"==l&&(b[c[k]]=!1)}}return b}
function Da(a){a:{var b;try{b=a.document.cookie}catch(k){b=""}if(a=b)for(a=a.split(";"),b=0;b<a.length;b++){var c=a[b].trim(),d=c.indexOf("="),e;if(e=-1!=d)e=c.substring(0,d).trim(),e="AMP_EXP"==ba(e,void 0);if(e){a=c.substring(d+1).trim();a=ba(a,a);break a}}a=null}var f=a,g=f?f.split(/\s*,\s*/g):[];a=Object.create(null);for(b=0;b<g.length;b++)0!=g[b].length&&("-"==g[b][0]?a[g[b].substr(1)]=!1:a[g[b]]=!0);return a}
function Ea(a,b){a.experimentBranches=a.experimentBranches||{};var c={},d;for(d in b)if(b.hasOwnProperty(d))if(a.experimentBranches.hasOwnProperty(d))c[d]=a.experimentBranches[d];else if(!b[d].isTrafficEligible||!b[d].isTrafficEligible(a))a.experimentBranches[d]=null;else if(!a.experimentBranches[d]&&G(a,d)){var e=b[d].branches,f=e;a.experimentBranches[d]=f[Math.floor(Math.random()*f.length)]||null;c[d]=a.experimentBranches[d]}}
function H(a,b){return a.experimentBranches?a.experimentBranches[b]:null}function Fa(a,b,c){a.experimentBranches=a.experimentBranches||{};var d=!!c,e=G(a,b),d=!(void 0!==d?!d:e);d!=e&&(Ca(a)[b]=d);a.experimentBranches[b]=c};function Ga(a){for(var b=[],c=0;a&&1==a.nodeType&&25>c;){var d="";a.id&&(d="/"+a.id);var e=a.nodeName.toLowerCase();b.push(""+e+d+Ha(a));c++;a=a.parentElement}return b.join()}function Ha(a){for(var b=a.nodeName,c=0,d=0,e=a.previousElementSibling;e&&25>d&&100>c;)e.nodeName==b&&d++,c++,e=e.previousElementSibling;return 25>d&&100>c?"."+d:""};function I(){var a,b;this.promise=new Promise(function(c,d){a=c;b=d});this.resolve=a;this.reject=b}function Ia(a){return new Promise(function(b){b(a())})};function J(a){if(a.nodeType){var b=Ja((a.ownerDocument||a).defaultView);if(b)return b}return K(a,"url-replace")}function Ka(a,b){var c=La(a);Ja(a);Ma(a,a,function(){return b});L(a,"url-replace")}function Ja(a){var b=La(a);return a!=b&&Na(a,"url-replace")?L(a,"url-replace"):null}function M(a,b){a=La(a);return L(a,b)}function K(a,b){a=O(a);a=Oa(a);return L(a,b)}function Pa(a,b){return Qa(Oa(a),b)}function La(a){return a.__AMP_TOP||a}
function O(a){return a.nodeType?M((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}function Oa(a){a=O(a);return a.isSingleDoc()?a.win:a}function L(a,b){Na(a,b);var c=Sa(a);a=c[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj}function Ma(a,b,c){var d=Sa(a),e=d["url-replace"];e||(e=d["url-replace"]={obj:null,promise:null,resolve:null,context:null,ctor:null});e.ctor||e.obj||(e.ctor=c,e.context=b,e.resolve&&L(a,"url-replace"))}
function Ta(a,b){var c=Qa(a,b);if(c)return c;var d=new I,e=d.promise,f=d.resolve;Sa(a)[b]={obj:null,promise:e,resolve:f,context:null,ctor:null};return e}function Qa(a,b){var c=Sa(a)[b];if(c){if(c.promise)return c.promise;L(a,b);return c.promise=Promise.resolve(c.obj)}return null}function Sa(a){var b=a.services;b||(b=a.services={});return b}
function Ua(a){a=Sa(a);var b={},c;for(c in a)if(b.id=c,Object.prototype.hasOwnProperty.call(a,b.id)){var d=a[b.id];d.obj?Va(b.id,d.obj):d.promise&&d.promise.then(function(a){return function(b){return Va(a.id,b)}}(b));b={id:b.id}}}function Va(a,b){if("function"==typeof b.dispose)try{b.dispose()}catch(c){z().error("SERVICE","failed to dispose service",a,c)}}function Na(a,b){a=a.services&&a.services[b];return!(!a||!a.ctor&&!a.obj)};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
var Wa={"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#x27;","`":"&#x60;"},Xa=/(&|<|>|"|'|`)/g;function Ya(a,b,c){a=a.createElement(b);for(var d in c)a.setAttribute(d,c[d]);return a}function Za(a,b){for(var c,d=a;d&&d!==c;d=d.parentElement)if(b(d))return d;return null}function $a(a){var b="A";if(a.closest)return a.closest(b);b=b.toUpperCase();return Za(a,function(a){return a.tagName==b})}function ab(a){return a?a.replace(Xa,bb):a}function bb(a){return Wa[a]};var cb=[];function db(a){return eb(a,"amp-analytics-instrumentation","amp-analytics",void 0).then(function(a){return y().assert(a,"Service %s was requested to be provided through %s, but %s is not loaded in the current page. To fix this problem load the JavaScript file for %s in this page.","amp-analytics-instrumentation","amp-analytics","amp-analytics","amp-analytics")})}
function eb(a,b,c,d){var e=O(a),f=Pa(a,b);return f?f:e.whenBodyAvailable().then(function(){var a;a=e.win;a=cb.includes(c)?M(a,"extensions").waitForExtension(a,c):Promise.resolve();return a}).then(function(){var f;d?f=Pa(a,b):(f=e.win,f=f.ampExtendedElements&&f.ampExtendedElements[c]?Ta(Oa(a),b):null);return f})};function fb(a){var b=!0;if(b=void 0===b?!1:b){var c=O(a);gb(c.win).installExtensionForDoc(c,"amp-analytics")}return db(a)}function hb(a){return eb(a,"amp-analytics-instrumentation","amp-analytics")}function P(a){return K(a,"documentInfo").get()}function gb(a){return M(a,"extensions")}function ib(a){return K(a,"resources")}function Q(a){return M(a,"timer")}function R(a){return K(a,"viewer")};function jb(a,b){var c="AMP_ECID_GOOGLE",d="_ga",e=isNaN(b)||null==b?1E3:b,f=Ta(Oa(a),"cid").then(function(a){if(a)return a.get({scope:c,createCookieIfNotPresent:!0,cookieName:d},Promise.resolve(void 0)).catch(function(a){z().error("AD-CID",a)})});return Q(a.win).timeoutPromise(e,f,"cid timeout").catch(function(a){z().warn("AD-CID",a)})};function S(a){var b;try{return JSON.parse(a)}catch(c){b&&b(c)}};var kb={"AMP-CAROUSEL":"ac","AMP-FX-FLYING-CARPET":"fc","AMP-LIGHTBOX":"lb","AMP-STICKY-AD":"sa"},lb={visible:"1",hidden:"2",prerender:"3",unloaded:"5"},T={name:"trunc",value:"1"};function mb(a){var b=a.element.getAttribute("type"),c=a.win;return("doubleclick"==b||"adsense"==b)&&G(c,"a4aProfilingRate")}
function nb(a,b){for(var c=a.element,d=a.win,e=a.getPageLayoutBox(),f=0;d!=d.parent&&100>f;)d=d.parent,f++;var g=f,k=ob(c),l=c.getAttribute("data-experiment-id");b&&(l=pb(b,l));return{adf:na(Ga(c)),nhd:g,eid:l,adx:e.left,ady:e.top,oid:"2",act:k.length?k.join():null}}
function qb(a,b){var c=rb;return ib(a.document).getMeasuredResources(a,function(a){var c="AMP-AD"==a.element.tagName&&a.element.getAttribute("type")==b;if(c)return!0;var d=Object.keys(kb).includes(a.element.tagName)&&!!a.element.querySelector("amp-ad[type="+b+"]");return d}).then(function(a){return Promise.all(a.map(function(a){var c;if("AMP-AD"==a.element.tagName)c=a.element;else if(c=a.element.querySelector("amp-ad[type="+b+"]"),ma(c.tagName,"AMP-"),c.createdCallback)c=Promise.resolve(c);else{if(!c.__AMP_UPG_PRM){var d=
new I;c.__AMP_UPG_PRM=d.promise;c.__AMP_UPG_RES=d.resolve}c=c.__AMP_UPG_PRM}return c}))}).then(function(a){return a.reduce(function(a,b){var d=c(b);(a[d]||(a[d]=[])).push(b.getImpl());return a},{})})}
function sb(a,b,c){return Promise.all([jb(b),R(b).getReferrerUrl()]).then(function(d){var e=d[0],f=P(b);a.gaGlobal=a.gaGlobal||{cid:e,hid:f.pageViewId};var g=a.screen,k=K(b,"viewport"),l=k.getRect(),m=k.getSize(),n=R(b).getVisibilityState(),p=tb(Ba(a)),e=ub(a,e,b),t=a.gaGlobal.cid||null,v=a.gaGlobal.hid||null,u=l.width,B=l.height,E=g?g.availWidth:null,D=g?g.availHeight:null,ta=g?g.colorDepth:null,gd=g?g.width:null,g=g?g.height:null,hd=-(new Date).getTimezoneOffset(),Ra;try{Ra=a.history.length}catch(xe){Ra=
0}var id=a!=a.top?m.width:null,jd=a!=a.top?m.height:null,kd=lb[n]||"0",ld=k.getScrollLeft(),md=k.getScrollTop(),ua=0,N=a.document;a.SVGElement&&N.createElementNS&&(ua|=vb);N=N.createElement("iframe");N.sandbox&&N.sandbox.supports&&(N.sandbox.supports("allow-top-navigation-by-user-activation")&&(ua|=wb),N.sandbox.supports("allow-popups-to-escape-sandbox")&&(ua|=xb));return{is_amp:"3",amp_v:"1527021682973",d_imp:"1",c:e,ga_cid:t,ga_hid:v,dt:c,biw:u,bih:B,u_aw:E,u_ah:D,u_cd:ta,u_w:gd,u_h:g,
u_tz:hd,u_his:Ra,isw:id,ish:jd,art:"0"==p?null:p,vis:kd,scr_x:ld,scr_y:md,bc:ua||null,debug_experiment_id:(/(?:#|,)deid=(\d+)/i.exec(a.location.hash)||[])[1]||null,url:f.canonicalUrl,top:a!=a.top?yb(a):null,loc:a.location.href==f.canonicalUrl?null:a.location.href,ref:d[1]||null}})}function zb(a,b,c){var d=nb(a,void 0);return sb(a.win,a.getAmpDoc(),b).then(function(a){Object.assign(c,d,a);return Ab(c,b)})}
function Ab(a,b){var c=[],d=T&&null!=T.value&&""!==T.value?encodeURIComponent(T.name)+"="+encodeURIComponent(String(T.value)):null,e=16325;d&&(e-=d.length+1);for(var f=Object.keys(a),g=0;g<f.length;g++){var k=f[g],l=a[k];if(null!=l&&""!==l){var k=encodeURIComponent(k)+"=",l=encodeURIComponent(String(l)),m=k.length+l.length+1;if(m>e){(a=l.substr(0,e-k.length-1).replace(/%\w?$/,""))&&c.push(k+a);d&&c.push(d);break}c.push(k+l);e-=m}}c=(c.length?"https://securepubads.g.doubleclick.net/gampad/ads?"+c.join("&"):
"https://securepubads.g.doubleclick.net/gampad/ads")+"&dtd=";b=Date.now()-b;return c+(1E6<=b?"M":0<=b?b:"-M")}function yb(a){var b=a.location.ancestorOrigins;if(b){var c=a.location.origin,d=b[b.length-1];if(c==d)return a.top.location.hostname;var e=Bb(a);return e==a||c==b[b.length-2]?C(e.document.referrer).hostname:C(d).hostname}try{return a.top.location.hostname}catch(f){}a=Bb(a);try{return C(a.document.referrer).hostname}catch(f){}return null}
function Bb(a){for(var b=0;a.parent!=a.parent.parent&&100>b;)a=a.parent,b++;return a}function ub(a,b,c){if(!a.ampAdPageCorrelator){var d;d=b;var e=P(c||a.document).pageViewId,e=Number(e||0);d=d?e+d.replace(/\D/g,"")%1E6*1E6:Math.floor(4503599627370496*Math.random());a.ampAdPageCorrelator=d}return a.ampAdPageCorrelator}function Cb(a,b){return A({on:a,request:"csi",sampleSpec:{sampleOn:"a4a-csi-${pageViewId}",threshold:1},selector:"amp-ad",selectionMethod:"closest",extraUrlParams:b})}
function Db(a){if(!a.has("X-AmpAnalytics"))return null;try{var b=JSON.parse(a.get("X-AmpAnalytics"));Array.isArray(b.url);var c=b.url;if(!c.length)return null;for(var d={transport:{beacon:!1,xhrpost:!1},triggers:{continuousVisible:{on:"visible",visibilitySpec:{selector:"amp-ad",selectionMethod:"closest",visiblePercentageMin:50,continuousTimeMin:1E3}}}},e={},f=1;f<=c.length;f++)e["visibility"+f]=""+c[f-1];d.requests=e;d.triggers.continuousVisible.request=Object.keys(e);return d}catch(g){z().error("AMP-A4A",
"Invalid analytics",g,a.get("X-AmpAnalytics"))}return null}function pb(a,b){var c=a.filter(function(a){return Number(a)}).join(",");b=b||"";return b+(b&&c?",":"")+c}
function Eb(a,b,c,d,e,f,g){var k=ub(a),l=Number(b.getAttribute("data-amp-slot-index"));a=encodeURIComponent(b.getAttribute("data-experiment-id"));var m=b.getAttribute("type"),n="https://csi.gstatic.com/csi?s=a4a"+("&c="+k+"&slotId="+l+"&qqid."+l+"="+d)+("&dt="+g)+("null"!=a?"&e."+l+"="+a:"")+("&rls=1527021682973&adt."+l+"="+m);f=Math.round(f);var p=e?"Friendly":"CrossDomain";c.triggers.continuousVisibleIniLoad={on:"ini-load",selector:"amp-ad",selectionMethod:"closest",request:"iniLoadCsi"};
c.triggers.continuousVisibleRenderStart={on:"render-start",selector:"amp-ad",selectionMethod:"closest",request:"renderStartCsi"};c.requests.iniLoadCsi=n+("&met.a4a."+l+"=iniLoadCsi"+p+"."+f);c.requests.renderStartCsi=n+("&met.a4a."+l+"=renderStartCsi"+p+"."+f);c.requests.visibilityCsi=n+("&met.a4a."+l+"=visibilityCsi."+f);c.triggers.continuousVisible.request.push("visibilityCsi")}
function ob(a){var b={};a=a.parentElement;for(var c=0;a&&20>c;a=a.parentElement,c++){var d=a.tagName.toUpperCase();kb[d]&&(b[kb[d]]=!0)}return Object.keys(b)}function tb(a){return{production:"0",control:"1",canary:"2"}[a]||null}var Fb=/\.google\.(?:com?\.)?[a-z]{2,3}$/;
function Gb(a,b,c,d,e){c=void 0===c?1:c;e=void 0===e?Date.now():e;d=Hb(a,b,d);return M(a,"xhr").fetchJson(d,{mode:"cors",method:"GET",ampCors:!1,credentials:"include"}).then(function(a){return a.json()}).then(function(d){var f=d.newToken,k=d["1p_jar"]||"",l=d.pucrd||"",m=parseInt(d.freshLifetimeSecs||"",10),n=parseInt(d.validLifetimeSecs||"",10),p=d.altDomain,t=Date.now()-e;return Fb.test(p)?c--?Gb(a,b,c,p,e):{fetchTimeMs:t}:0<m&&0<n&&"string"==typeof f?{token:f,jar:k,pucrd:l,freshLifetimeSecs:m,
validLifetimeSecs:n,fetchTimeMs:t}:{fetchTimeMs:t}}).catch(function(){return{}})}function Hb(a,b,c){!c&&a!=a.top&&a.location.ancestorOrigins&&(c=(a=Fb.exec(a.location.ancestorOrigins[a.location.ancestorOrigins.length-1]))&&a[0]||void 0);c=c||".google.com";var d=C(P(b).canonicalUrl).hostname;return"https://adservice"+c+"/adsid/integrator.json?domain="+d}function Ib(a){return/^https:\/\/([a-zA-Z0-9_-]+\.)?cdn\.ampproject\.org((\/.*)|($))+/.test(a.location.origin)}var vb=1,wb=2,xb=4;function Jb(a,b){var c=R(b).getParam("exp")||q(a.location.search).exp;if(!c)return null;var d=["doubleclick"==(b.getAttribute("type")||"").toLowerCase()?"da":"aa","a4a"],e,f;d.forEach(function(a){return e=e||(f=(new RegExp("(?:^|,)"+a+":(-?\\d+)")).exec(c))&&f[1]});return e||null}function Kb(a){return a?a.split(","):[]}function Lb(a){return Kb(a.getAttribute("data-experiment-id")).some(function(a){return"117152632"===a})}function Mb(a){return a.every(function(a){return!isNaN(parseInt(a,10))})}
function Nb(a,b){if(a){var c=b.getAttribute("data-experiment-id");c&&Mb(Kb(c))?b.setAttribute("data-experiment-id",pb([a],c)):b.setAttribute("data-experiment-id",a)}};var Ob={"-1":"117152632",0:null,3:"21060728",4:"21060729",5:"21061787",6:"21061788",7:"117152666",8:"117152667"};function Pb(){}h=Pb.prototype;h.isCdnProxy=function(a){return Ib(a)};h.unconditionedExperimentSelection=function(a,b){this.selectAndSetUnconditionedExp(a,b,["21061372","21061373"],"expUnconditionedCanonicalHoldback")};h.selectAndSetUnconditionedExp=function(a,b,c,d){if(c=this.maybeSelectExperiment(a,b,c,d))Nb(c,b),Fa(a,d,c)};
h.isA4aEnabled=function(a,b,c){function d(a){return y().warn("amp-ad-network-doubleclick-impl",a+" is no longer supported for DoubleClick.Please refer to https://github.com/ampproject/amphtml/issues/11834 for more information")}this.unconditionedExperimentSelection(a,b);var e="useSameDomainRenderingUntilDeprecated",f=e in b.dataset||(S(b.getAttribute("json"))||{})[e];f&&d(e);c&&d("remote.html");var g,k=Jb(a,b)||"";if(!this.isCdnProxy(a))return"21061373"!=H(a,"expUnconditionedCanonicalHoldback")?(Nb("21060933",
b),!0):!1;void 0!=k&&(g=Ob[k],"117152666"!=g&&"117152667"!=g||!a.document.querySelector("meta[name=amp-ad-enable-refresh]")&&!a.document.querySelector("amp-ad[type=doubleclick][data-enable-refresh]")?z().info("amp-ad-network-doubleclick-impl","url experiment selection "+k+": "+g+"."):g=void 0);g&&(Nb(g,b),Fa(a,"expDoubleclickA4A",g));return G(a,"rollback-delayed-fetch-deprecation")||"21061788"==g?!!b.getAttribute("rtc-config")||!(f||c):!0};
h.maybeSelectExperiment=function(a,b,c,d){b={};b[d]={isTrafficEligible:function(){return!0},branches:c};Ea(a,b);return H(a,d)};new Pb;function Qb(a,b,c){return H(a,c||"expDoubleclickA4A")==b};var Rb={google:"https://cdn.ampproject.org/amp-ad-verifying-keyset.json","google-dev":"https://cdn.ampproject.org/amp-ad-verifying-keyset-dev.json",cloudflare:"https://amp.cloudflare.com/amp-ad-verifying-keyset.json","cloudflare-dev":"https://amp.cloudflare.com/amp-ad-verifying-keyset-dev.json"};var Sb,Tb="Webkit webkit Moz moz ms O o".split(" ");function Ub(a,b,c){if(ma(b,"--"))return b;Sb||(Sb=ka());var d=Sb[b];if(!d||c){d=b;if(void 0===a[b]){var e=b.charAt(0).toUpperCase()+b.slice(1);a:{for(var f=0;f<Tb.length;f++){var g=Tb[f]+e;if(void 0!==a[g]){e=g;break a}}e=""}var k=e;void 0!==a[k]&&(d=k)}c||(Sb[b]=d)}return d}function Vb(a,b,c){var d;(b=Ub(a.style,b,void 0))&&(a.style[b]=d?c+d:c)}function U(a,b){for(var c in b)Vb(a,c,b[c])}
function Wb(a,b){var c={};b.forEach(function(a){c[a]=null});U(a,c)};function Xb(a,b,c){hb(a).then(function(d){d&&d.triggerEventForTarget(a,b,c)})};var Yb;function Zb(a,b,c){function d(a){try{return g(a)}catch(n){throw self.reportError(n),n;}}var e=void 0,f=a,g=c,k=$b(),l=!1;e&&(l=e.capture);f.addEventListener(b,d,k?e:l);return function(){f&&f.removeEventListener(b,d,k?e:l);d=f=g=null}}function $b(){if(void 0!==Yb)return Yb;Yb=!1;try{var a={get capture(){Yb=!0}};self.addEventListener("test-options",null,a);self.removeEventListener("test-options",null,a)}catch(b){}return Yb};function ac(a,b,c){var d=c,e=Zb(a,b,function(a){try{d(a)}finally{d=null,e()}});return e}function bc(a){var b,c;if(a.complete||"complete"==a.readyState||a.document&&"complete"==a.document.readyState)return Promise.resolve(a);var d=new Promise(function(d,f){var e=a.tagName;b="AUDIO"===e||"VIDEO"===e?ac(a,"loadstart",d):ac(a,"load",d);e&&(c=ac(a,"error",f))});return d.then(function(){c&&c();return a},function(){b&&b();var c=a;c&&c.src&&(c=c.src);throw y().createError("Failed to load:",c);})};self.AMPErrors=self.AMPErrors||[];function cc(a){return a?"string"==typeof a?ma(a,"CANCELLED"):"string"==typeof a.message?ma(a.message,"CANCELLED"):!1:!1};function dc(a,b,c){return bc(a).then(function(){return ec(a,b,c)})}function ec(a,b,c){var d=a.performance&&a.performance.timing;if(d&&0!=d.navigationStart){var e=void 0===c?d[b]:d[c]-d[b];if(fa(e)&&!(0>e))return e}}function fc(a,b){var c=a.performance&&a.performance.navigation;if(c&&void 0!==c[b])return c[b]}function gc(a){this.ampdoc=a;this.ka=this.la=void 0;this.F=Object.create(null);this.ua=!1;hc(this)}h=gc.prototype;h.initialize=function(){};
h.get=function(a){this.ua||(this.initialize(),this.ua=!0);return this.F[a]};h.set=function(a,b){a.indexOf("RETURN");this.F[a]=this.F[a]||{sync:void 0,async:void 0};this.F[a].sync=b;this.ka=this.la=void 0;return this};h.setAsync=function(a,b){a.indexOf("RETURN");this.F[a]=this.F[a]||{sync:void 0,async:void 0};this.F[a].async=b;this.ka=this.la=void 0;return this};h.setBoth=function(a,b,c){return this.set(a,b).setAsync(a,c)};
h.getExpr=function(a,b){var c=this;this.ua||(this.initialize(),this.ua=!0);var d=a?Object.keys(a):null;if(d&&0<d.length){var e=Object.keys(this.F);d.forEach(function(a){void 0===c.F[a]&&e.push(a)});return ic(this,e,b)}this.la||b||(this.la=ic(this,Object.keys(this.F)));!this.ka&&b&&(this.ka=ic(this,Object.keys(this.F),b));return b?this.ka:this.la};
function ic(a,b,c){hc(a)&&(b=b.filter(function(b){return hc(a).includes(b)}));b.sort(function(a,b){return b.length-a.length});var d=b.join("|"),e="\\$?("+d+")";c||(e+="(?:\\(((?:\\s*[0-9a-zA-Z-_.]*\\s*(?=,|\\)),?)*)\\s*\\))?");return new RegExp(e,"g")}
function hc(a){if(a.Ia)return a.Ia;var b=a.ampdoc.getRootNode().head;if(!b)return null;var c=b.querySelector('meta[name="amp-allowed-url-macros"]');if(!c)return null;a.Ia=c.getAttribute("content").split(",").map(function(a){return a.trim()});return a.Ia};var jc="RANDOM COUNTER CANONICAL_URL CANONICAL_HOST CANONICAL_HOSTNAME CANONICAL_PATH DOCUMENT_REFERRER TITLE AMPDOC_URL AMPDOC_HOST AMPDOC_HOSTNAME SOURCE_URL SOURCE_HOST SOURCE_HOSTNAME SOURCE_PATH PAGE_VIEW_ID CLIENT_ID VARIANT VARIANTS SHARE_TRACKING_INCOMING SHARE_TRACKING_OUTGOING TIMESTAMP TIMEZONE TIMEZONE_CODE SCROLL_TOP SCROLL_LEFT SCROLL_HEIGHT SCROLL_WIDTH VIEWPORT_HEIGHT VIEWPORT_WIDTH SCREEN_WIDTH SCREEN_HEIGHT AVAILABLE_SCREEN_HEIGHT AVAILABLE_SCREEN_WIDTH SCREEN_COLOR_DEPTH DOCUMENT_CHARSET BROWSER_LANGUAGE VIEWER TOTAL_ENGAGED_TIME AMP_VERSION USER_AGENT FIRST_CONTENTFUL_PAINT FIRST_VIEWPORT_READY MAKE_BODY_VISIBLE".split(" ");
function kc(a,b){gc.call(this,a);this.gb=J(a).getVariableSource();this.m=b}aa(kc,gc);
kc.prototype.initialize=function(){var a=this;this.set("AD_NAV_TIMING",function(b,c){y().assert(b,"The first argument to AD_NAV_TIMING, the start attribute name, is required");return ec(a.m,b,c)}).setAsync("AD_NAV_TIMING",function(b,c){y().assert(b,"The first argument to AD_NAV_TIMING, the start attribute name, is required");return dc(a.m,b,c)});this.set("AD_NAV_TYPE",function(){return fc(a.m,"type")});this.set("AD_NAV_REDIRECT_COUNT",function(){return fc(a.m,"redirectCount")});this.set("HTML_ATTR",
this.hb.bind(this));for(var b=0;b<jc.length;b++){var c=jc[b],d=this.gb.get(c);this.set(c,d.sync).setAsync(c,d.async)}};
kc.prototype.hb=function(a,b){var c=20,d=10,e=10,f="A4AVariableSource",g=Array.prototype.slice.call(arguments,1);if(!a||!g.length)return"[]";if(g.length>e)return y().error(f,"At most "+e+" may be requested."),"[]";a=decodeURI(a);var k;try{k=this.m.document.querySelectorAll(a)}catch(u){return y().error(f,"Invalid selector: "+a),"[]"}if(k.length>c)return y().error(f,"CSS selector may match at most "+(c+" elements.")),"[]";for(var l=[],m=0;m<k.length&&l.length<d;++m){for(var n={},p=!1,t=0;t<g.length;++t){var v=
g[t];k[m].hasAttribute(v)&&(n[v]=k[m].getAttribute(v),p=!0)}p&&l.push(n)}return JSON.stringify(l)};function lc(a){return"fixed"==a||"fixed-height"==a||"responsive"==a||"fill"==a||"flex-item"==a||"fluid"==a||"intrinsic"==a}function mc(a){a=parseFloat(a);return fa(a)?a:void 0};function nc(a){if("undefined"!==typeof TextDecoder)return(new TextDecoder("utf-8")).decode(a);for(var b=new Uint8Array(a.buffer||a),c=Array(b.length),d=0;d<b.length;d++)c[d]=String.fromCharCode(b[d]);var e=c.join("");return decodeURIComponent(escape(e))}function oc(a){for(var b=new Uint8Array(a.length),c=0;c<a.length;c++){var d=a.charCodeAt(c);b[c]=d}return b};function pc(a,b){this.m=a;this.mb=b;this.oa=M(a,"crypto").isPkcsAvailable()?{}:null;this.X=a.performance&&a.performance.now?a.performance.now.bind(a.performance):Date.now}pc.prototype.loadKeyset=function(a){if(this.oa&&!this.oa[a]){var b={},c=qc(this,b,a,null);this.oa[a]={promise:c,keys:b}}};
pc.prototype.verify=function(a,b,c){var d=/^([A-Za-z0-9._-]+):([A-Za-z0-9._-]+):([A-Za-z0-9+/]{341}[AQgw]==)$/;if(!b.has("AMP-Fast-Fetch-Signature"))return Promise.resolve(1);var e=b.get("AMP-Fast-Fetch-Signature");b=d.exec(e);return b?this.verifyCreativeAndSignature(b[1],b[2],oc(atob(b[3])),a,c):(y().error("AMP-A4A","Invalid signature header: "+e.split(":")[0]),Promise.resolve(3))};
pc.prototype.verifyCreativeAndSignature=function(a,b,c,d,e){var f=this;if(!this.oa)return Promise.resolve(4);var g=this.oa[a];return g.promise.then(function(k){if(!k)return 1;var l=g.keys[b];return void 0===l?(g.promise=qc(f,g.keys,a,b).then(function(a){void 0===g.keys[b]&&(g.keys[b]=null);return a}),f.verifyCreativeAndSignature(a,b,c,d,e)):null===l?2:l.then(function(b){if(!b)return 1;var g=M(f.m,"crypto"),k=f.X();return g.verifyPkcs(b,c,d).then(function(b){var c=f.X();return b?(e("signatureVerifySuccess",
{"met.delta.AD_SLOT_ID":c-k,"signingServiceName.AD_SLOT_ID":a}),0):3},function(a){a=a&&a.message;z().error("AMP-A4A","Failed to verify signature: "+a);return 1})})})};
function qc(a,b,c,d){var e=a.mb[c];null!=d&&(e+="?kid="+encodeURIComponent(d));return M(a.m,"xhr").fetchJson(e,{mode:"cors",method:"GET",ampCors:!1,credentials:"omit"}).then(function(d){d.headers.get("Content-Type");return d.json().then(function(d){if(!d||!Array.isArray(d.keys))return rc(c,"Key set ("+JSON.stringify(d)+') has no "keys"'),!1;d.keys.forEach(function(d){d&&"string"==typeof d.kid?void 0===b[d.kid]&&(b[d.kid]=M(a.m,"crypto").importPkcsKey(d).catch(function(a){var b=JSON.stringify(d);rc(c,
"Failed to import key ("+b+"): "+(a&&a.message));return null})):rc(c,"Key ("+JSON.stringify(d)+') has no "kid"')});return!0},function(a){rc(c,"Failed to parse JSON: "+(a&&a.response));return!1})},function(a){a&&a.response&&rc(c,"Status code "+a.response.status);return!1})}function rc(a,b){z().error("AMP-A4A","Signing service error for "+a+": "+b)};function sc(a,b,c,d){var e=Date.now(),f=b.getAttribute("width"),g=b.getAttribute("height");d=d?d:{};d.width=mc(f);d.height=mc(g);b.getAttribute("title")&&(d.title=b.getAttribute("title"));var k=a.location.href;"about:srcdoc"==k&&(k=a.parent.location.href);var l=P(b),f=R(b),m=f.getUnconfirmedReferrerUrl(),n=b.getPageLayoutBox(),g=d,p=l.sourceUrl,t=l.canonicalUrl,v=l.pageViewId,u={href:k},B=b.tagName,E={localDev:!1,development:r(void 0).development,filter:r(void 0).filter,minified:!0,lite:r(void 0).lite,
test:!1,log:r(void 0).log,version:r(void 0).version,rtvVersion:r(void 0).rtvVersion},D=a;g._context=A({ampcontextVersion:"1527021682973",ampcontextFilepath:pa+"/1527021682973/ampcontext-v0.js",sourceUrl:p,referrer:m,canonicalUrl:t,pageViewId:v,location:u,startTime:e,tagName:B,mode:E,canary:!(!D.AMP_CONFIG||!D.AMP_CONFIG.canary),hidden:!f.isVisible(),initialLayoutRect:n?{left:n.left,top:n.top,width:n.width,height:n.height}:null,initialIntersection:b.getIntersectionChangeEntry(),
domFingerprint:na(Ga(b)),experimentToggles:Ca(a),sentinel:c});var ta=b.getAttribute("src");ta&&(d.src=ta);return d};function tc(a,b,c){var d=!0,d=void 0===d?!1:d;c=void 0===c?!1:c;var e=a.ownerDocument,f=Ya(e,"amp-analytics",A({sandbox:"true",trigger:c?"":"immediate"})),g=Ya(e,"script",A({type:"application/json"}));g.textContent=JSON.stringify(b);f.appendChild(g);f.CONFIG=b;d?(b=gb(a.ownerDocument.defaultView),d=O(a),b.installExtensionForDoc(d,"amp-analytics")):hb(a).then(function(){});a.appendChild(f);return f};var uc={"AMP-FX-FLYING-CARPET":!0,"AMP-LIGHTBOX":!0,"AMP-STICKY-AD":!0,"AMP-LIGHTBOX-GALLERY":!0};function vc(a,b){return eb(a,"consentPolicyManager","amp-consent").then(function(a){return a?a.whenPolicyResolved(b):null})};function wc(a){var b="nameframe",c=b||"frame";a.defaultBootstrapSubDomain=a.defaultBootstrapSubDomain||"d-"+xc(a);return"https://"+a.defaultBootstrapSubDomain+("."+qa+"/1527021682973/")+(c+".html")}function xc(a){var b;if(a.crypto&&a.crypto.getRandomValues){var c=new Uint32Array(2);a.crypto.getRandomValues(c);b=String(c[0])+c[1]}else b=String(a.Math.random()).substr(2)+"0";return b}function yc(){for(var a=window,b=0,c=a;c&&c!=c.parent;c=c.parent)b++;return String(b)+"-"+xc(a)};var zc=null,Ac=null;function Bc(a,b){void 0===a["3pla"]&&(a["3pla"]=0);a["3pla"]++;zc=zc||new Promise(function(a){return Ac=a});Q(a).timeoutPromise(1E3,b).catch(function(){}).then(function(){--a["3pla"]||(Ac(),Ac=zc=null)})};function Cc(){this.A=null}h=Cc.prototype;h.add=function(a){var b=this;this.A||(this.A=[]);this.A.push(a);return function(){b.remove(a)}};h.remove=function(a){this.A&&(a=this.A.indexOf(a),-1<a&&this.A.splice(a,1))};h.removeAll=function(){this.A&&(this.A.length=0)};h.fire=function(a){if(this.A)for(var b=this.A,c=0;c<b.length;c++)(0,b[c])(a)};h.getHandlerCount=function(){return this.A?this.A.length:0};function Dc(){this.M=ka();this.C=null}h=Dc.prototype;h.get=function(a){return this.M[a]||null};h.whenSignal=function(a){var b=this.C&&this.C[a];if(!b){var c=this.M[a];null!=c?b={promise:"number"==typeof c?Promise.resolve(c):Promise.reject(c)}:(c=new I,b={promise:c.promise,resolve:c.resolve,reject:c.reject});this.C||(this.C=ka());this.C[a]=b}return b.promise};
h.signal=function(a,b){if(null==this.M[a]){var c=b||Date.now();this.M[a]=c;(a=this.C&&this.C[a])&&a.resolve&&(a.resolve(c),a.resolve=void 0,a.reject=void 0)}};h.rejectSignal=function(a,b){null==this.M[a]&&(this.M[a]=b,(a=this.C&&this.C[a])&&a.reject&&(a.reject(b),a.resolve=void 0,a.reject=void 0))};h.reset=function(a){this.M[a]&&delete this.M[a];var b=this.C&&this.C[a];b&&!b.resolve&&delete this.C[a]};function Ec(a,b,c,d){return{left:a,top:b,width:c,height:d,bottom:b+d,right:a+c,x:a,y:b}}function Fc(a){for(var b=-Infinity,c=Infinity,d=-Infinity,e=Infinity,f=0;f<arguments.length;f++){var g=arguments[f];if(g&&(b=Math.max(b,g.left),c=Math.min(c,g.left+g.width),d=Math.max(d,g.top),e=Math.min(e,g.top+g.height),c<b||e<d))return null}return Infinity==c?null:Ec(b,d,c-b,e-d)}function Gc(a,b,c){return 0==b&&0==c||0==a.width&&0==a.height?a:Ec(a.left+b,a.top+c,a.width,a.height)};var Hc=["AMP-AD","AMP-ANALYTICS","AMP-PIXEL","AMP-AD-EXIT"],Ic;function Jc(a,b){Kc(a,b)}
function Lc(a,b,c,d){function e(){a.contentWindow.addEventListener("securitypolicyviolation",function(a){z().warn("FIE","security policy violation",a)})}var f=La(a.ownerDocument.defaultView),g=gb(f);Vb(a,"visibility","hidden");a.setAttribute("referrerpolicy","unsafe-url");c.extensionIds&&c.extensionIds.forEach(function(a){return g.preloadExtension(a)});var k=Mc(c);a.onload=function(){a.readyState="complete"};var l;void 0===Ic&&(Ic="srcdoc"in HTMLIFrameElement.prototype);if(Ic)a.srcdoc=k,l=bc(a),b.appendChild(a),
e();else{a.src="about:blank";b.appendChild(a);var m=a.contentWindow.document;m.open();e();m.write(k);l=bc(a.contentWindow);m.close()}var n;n=Nc(a)?Promise.resolve():new Promise(function(b){var c=f.setInterval(function(){Nc(a)&&(b(),f.clearInterval(c))},5);l.catch(function(a){x(a)}).then(function(){b();f.clearInterval(c)})});return n.then(function(){var b=new Oc(a,c,l);a.__AMP_EMBED__=b;g.installExtensionsInChildWindow(a.contentWindow,c.extensionIds||[],d);Pc(b);return b})}
function Nc(a){a=a.contentWindow&&a.contentWindow.document;return!!(a&&"loading"!=a.readyState&&"uninitialized"!=a.readyState&&a.body&&a.body.firstChild)}
function Mc(a){var b=a.html,c=b.toUpperCase(),d=c.indexOf("<HEAD");-1!=d&&(d=c.indexOf(">",d+1)+1);-1==d&&(d=c.indexOf("<BODY"));-1==d&&(d=c.indexOf("<HTML"),-1!=d&&(d=c.indexOf(">",d+1)+1));var e=[];0<d&&e.push(b.substring(0,d));e.push('<base href="'+ab(a.url)+'">');a.fonts&&a.fonts.forEach(function(a){e.push('<link href="'+ab(a)+'" rel="stylesheet" type="text/css">')});e.push("<meta http-equiv=Content-Security-Policy content=\"script-src 'none';object-src 'none';child-src 'none'\">");0<d?e.push(b.substring(d)):
e.push(b);return e.join("")}function Oc(a,b,c){this.iframe=a;this.win=a.contentWindow;this.spec=b;this.host=b.host||null;this.ob=Date.now();this.za=!1;this.Za=new Cc;this.na=this.host?this.host.signals():new Dc;this.rb=Promise.all([c,this.whenReady()])}h=Oc.prototype;h.destroy=function(){ib(this.iframe).removeForChildWindow(this.win);Ua(this.win)};h.getStartTime=function(){return this.ob};h.getUrl=function(){return this.spec.url};h.signals=function(){return this.na};h.whenReady=function(){return this.na.whenSignal("render-start")};
h.whenWindowLoaded=function(){return this.rb};h.whenIniLoaded=function(){return this.na.whenSignal("ini-load")};
function Pc(a){a.host?a.host.renderStarted():a.na.signal("render-start");Vb(a.iframe,"visibility","");a.win.document&&a.win.document.body&&(a.win.document.documentElement.classList.add("i-amphtml-fie"),U(a.win.document.body,{opacity:1,visibility:"visible",animation:"none"}));var b;b=a.host?a.host.getLayoutBox():Ec(0,0,a.win.innerWidth,a.win.innerHeight);Promise.all([a.whenReady(),Qc(a.iframe,a.win,b)]).then(function(){a.na.signal("ini-load")})}h.isVisible=function(){return this.za};
h.onVisibilityChanged=function(a){return this.Za.add(a)};function Kc(a,b){a.za!=b&&(a.za=b,a.Za.fire(a.za))}h.getBodyElement=function(){return(this.iframe.contentDocument||this.iframe.contentWindow.document).body};h.getResources=function(){return ib(this.iframe)};function Rc(a,b){var c;return a.getResources().measureMutateElement(a.iframe,b.measure||null,b.mutate)}
h.enterFullOverlayMode=function(){var a=this,b={background:"transparent",position:"absolute",top:"",left:"",width:"",height:"",bottom:"auto",right:"auto"};return Rc(this,{measure:function(){var c=a.iframe.getBoundingClientRect();Object.assign(b,{top:c.top+"px",left:c.left+"px",width:c.width+"px",height:c.height+"px"})},mutate:function(){U(a.iframe,{position:"fixed",left:0,right:0,top:0,bottom:0,width:"100vw",height:"100vh"});var c=a.getBodyElement(),d=b,e;for(e in d)c.style.setProperty(Ub(d,e),d[e].toString(),
"important")}})};h.leaveFullOverlayMode=function(){var a=this;return Rc(this,{mutate:function(){Wb(a.iframe,"position left right top bottom width height".split(" "));Wb(a.getBodyElement(),"position top left width height bottom right".split(" "))}})};function Qc(a,b,c){return ib(a).getResourcesInRect(b,c).then(function(a){var b=[];a.forEach(function(a){Hc.includes(a.element.tagName)||b.push(a.loadedOnce())});return Promise.all(b)})};function Sc(a){this.T=a}Sc.prototype.expand=function(a,b){if(!a.length)return Promise.resolve(a);var c=this.T.getExpr(b,!0),c=Tc(a,c);return c.length?Uc(this,a,c,b):Promise.resolve(a)};function Tc(a,b){var c=[];a.replace(b,function(a,b,f){a=a.length;var d=a+f-1;c.push({start:f,stop:d,name:b,length:a})});return c}
function Uc(a,b,c,d){function e(){for(var t="",v=[];g<b.length&&k<=c.length;){if(l&&g===l.start){var u=void 0;d&&d.hasOwnProperty(l.name)?u=d[l.name]:(u=a.T.get(l.name),u=u.async||u.sync);g=l.stop+1;l=c[++k];"("===b[g]?(g++,m++,f.push(u),t.length&&v.push(t),v.push(e())):(t.length&&v.push(t),v.push(Vc(u)));t=""}else if("`"===b[g])n?n=!1:(p=n=!0,y().assert(""===t.trim(),'The substring "'+t+'" was lost during url-replacement. Please ensure the url syntax is correct'),t=""),g++;else if(m&&","===b[g]&&
!n){if(t.length){var B=p?t:t.trim();v.push(B);p=!1}","===b[g+1]&&(v.push(""),g++);t="";g++}else if(")"!==b[g]||n)t+=b[g],g++;else{g++;m--;var E=f.pop(),D=p?t:t.trim();v.push(D);p=!1;return Vc(E,v)}g===b.length&&t.length&&v.push(t)}return Promise.all(v).then(function(a){return a.join("")}).catch(function(a){x(a);return""})}var f=[],g=0,k=0,l=c[k],m=0,n=!1,p=!1;return e()}
function Vc(a,b){var c;try{return c="function"===typeof a?b?Promise.all(b).then(function(b){return a.apply(null,b)}):Ia(a):Promise.resolve(a),c.then(function(a){return null==a?"":encodeURIComponent(a)}).catch(function(a){x(a);return""})}catch(d){return x(d),Promise.resolve("")}};var Wc={ANCESTOR_ORIGIN:!0};function Xc(a,b){this.ampdoc=a;this.T=b;this.eb=new Sc(this.T)}h=Xc.prototype;h.expandStringSync=function(a,b,c,d){return V(this,a,b,c,!0,d)};h.expandStringAsync=function(a,b){return V(this,a,b)};h.expandUrlSync=function(a,b,c,d){return Yc(a,V(this,a,b,c,!0,d))};h.expandUrlAsync=function(a,b,c){return V(this,a,b,void 0,void 0,c).then(function(b){return Yc(a,b)})};h.expandInputValueAsync=function(a){return Zc(this,a,!1)};
h.expandInputValueSync=function(a){return Zc(this,a,!0)};function Zc(a,b,c){"INPUT"==b.tagName&&(b.getAttribute("type")||"").toLowerCase();var d=$c(b);if(!d)return c?b.value:Promise.resolve(b.value);void 0===b["amp-original-value"]&&(b["amp-original-value"]=b.value);a=V(a,b["amp-original-value"]||b.value,void 0,void 0,c,d);return c?b.value=a:a.then(function(a){return b.value=a})}
function $c(a,b){if(a=a.getAttribute("data-amp-replace")){var c={};a.trim().split(/\s+/).forEach(function(a){!b||b.hasOwnProperty(a)?c[a]=!0:y().warn("URL","Ignoring unsupported replacement",a)});return c}}
h.maybeExpandLink=function(a,b){var c={CLIENT_ID:!0,QUERY_PARAM:!0},d=a.getAttribute("data-amp-addparams")||"",e=$c(a,c);if(e||d||b){var f=a["amp-original-href"]||a.getAttribute("href"),g=C(f);null==a["amp-original-href"]&&(a["amp-original-href"]=f);if(d)var k=q(d),f=xa(f,ya(k));a:if(k=P(this.ampdoc),g.origin==C(k.canonicalUrl).origin||g.origin==C(k.sourceUrl).origin)g=!0;else{if((k=this.ampdoc.getRootNode().querySelector("meta[name=amp-link-variable-allowed-origin]"))&&k.hasAttribute("content"))for(var k=
k.getAttribute("content").trim().split(/\s+/),l=0;l<k.length;l++)if(g.origin==C(k[l]).origin){g=!0;break a}g=!1}var m=g;if(!m)return e&&y().warn("URL","Ignoring link replacement",f," because the link does not go to the document's source, canonical, or whitelisted origin."),a.href=f;if(b){if(!e||!e.QUERY_PARAM){var n={QUERY_PARAM:!0};b=this.expandUrlSync(b,void 0,void 0,n)}g=q(b);f=xa(f,ya(g))}e&&(f=this.expandUrlSync(f,void 0,void 0,e));return a.href=f}};
function V(a,b,c,d,e,f){var g=G(a.ampdoc.win,"url-replacement-v2");if(g&&!d&&!e)return a.eb.expand(b,c,f);var k=a.T.getExpr(c),l,m=b.replace(k,function(b,g,k){var n=[];"string"==typeof k&&(n=k.split(/,\s*/));if(f&&!f[g])return b;var u;if(c&&g in c)u=c[g];else if(u=a.T.get(g))if(e){if(u=u.sync,!u)return y().error("UrlReplacements","ignoring async replacement key: ",g),""}else u=u.async||u.sync;var p;try{p="function"==typeof u?u.apply(null,n):u}catch(D){e&&(p=""),x(D)}if(p&&p.then){if(e)return y().error("UrlReplacements",
"ignoring promise value for key: ",g),"";var t=p.catch(function(a){x(a)}).then(function(a){m=m.replace(b,Wc[b]?a:null==a?"":encodeURIComponent(a));d&&(d[b]=a)});l=l?l.then(function(){return t}):t;return b}d&&(d[b]=p);return Wc[b]?p:null==p?"":encodeURIComponent(p)});l&&(l=l.then(function(){return m}));return e?m:l||Promise.resolve(m)}h.collectVars=function(a,b){var c=Object.create(null);return V(this,a,b,c).then(function(){return c})};
h.collectUnwhitelistedVarsSync=function(a){var b=a.getAttribute("src"),c=Object.create(null);this.expandStringSync(b,void 0,c);var d=Object.keys(c),e=$c(a);return e?d.filter(function(a){return!e[a]}):d};function Yc(a,b){var c=C(b,!0).protocol,d=C(a,!0).protocol;if(c!=d)return y().error("UrlReplacements","Illegal replacement of the protocol: ",a),a;y().assert(Aa(b),"The replacement url has invalid protocol: %s",b);return b}h.getVariableSource=function(){return this.T};var ad=["<script amp-ad-metadata type=application/json>",'<script type="application/json" amp-ad-metadata>',"<script type=application/json amp-ad-metadata>"],bd={CLIENT_CACHE:"client_cache",SAFEFRAME:"safeframe",NAMEFRAME:"nameframe"},cd=A({frameborder:"0",allowfullscreen:"",allowtransparency:"",scrolling:"no",marginwidth:"0",marginheight:"0"}),dd={adSlotCleared:"-1",urlBuilt:"1",adRequestStart:"2",adRequestEnd:"3",adResponseValidateStart:"5",renderFriendlyStart:"6",renderCrossDomainStart:"7",renderFriendlyEnd:"8",
renderCrossDomainEnd:"9",preAdThrottle:"10",renderSafeFrameStart:"11",throttled3p:"12",adResponseValidateEnd:"13",xDomIframeLoaded:"14",friendlyIframeLoaded:"15",adSlotCollapsed:"16",adSlotUnhidden:"17",layoutAdPromiseDelay:"18",signatureVerifySuccess:"19",networkError:"20",friendlyIframeIniLoad:"21",visHalf:"22",visHalfIniLoad:"23",firstVisible:"24",visLoadAndOneSec:"25",iniLoad:"26",resumeCallback:"27",visIniLoad:"29",upgradeDelay:"30",crossDomainIframeLoaded:"31"},ed={adRequestStart:"ad-request-start",
adRequestEnd:"ad-response-end",renderFriendlyStart:"ad-render-start",renderCrossDomainStart:"ad-render-start",renderSafeFrameStart:"ad-render-start",renderFriendlyEnd:"ad-render-end",renderCrossDomainEnd:"ad-render-end",friendlyIframeIniLoad:"ad-iframe-loaded",crossDomainIframeLoaded:"ad-iframe-loaded"};function fd(a,b,c){return function(d){for(var e=[],f=0;f<arguments.length;++f)e[f-0]=arguments[f];try{return a.apply(b,e)}catch(g){if(c)try{return e.unshift(g),c.apply(b,e)}catch(k){}}}}
function W(a){var b;b=AMP.BaseElement.call(this,a)||this;b.Sa=null;b.O=null;b.$=0;b.D=null;b.R=null;b.uiHandler=null;b.J=null;b.ha=!1;b.ca=null;b.j=null;b.N=null;b.V=b.getNonAmpCreativeRenderingMethod();b.Wa=!1;b.X=b.win.performance&&b.win.performance.now?b.win.performance.now.bind(b.win.performance):Date.now;b.jb=fd(b.emitLifecycleEvent,b,function(a,d){z().error("amp-a4a",b.element.getAttribute("type"),"Error on emitLifecycleEvent",a,d)});b.sentinel=yc();b.Y=!1;b.iframe=null;b.fromResumeCallback=
!1;b.safeframeVersion="1-0-23";b.isRefreshing=!1;b.isRelayoutNeededFlag=!1;b.Da=tb(Ba(b.win))||"-1";b.postAdResponseExperimentFeatures={};b.pa=null;b.$a=null;b.isSinglePageStoryAd=!1;return b}aa(W,AMP.BaseElement);h=W.prototype;h.getLayoutPriority=function(){var a=!this.element.getAmpDoc().isSingleDoc();return a?1:2};h.isLayoutSupported=function(a){return lc(a)};h.isRelayoutNeeded=function(){return this.isRelayoutNeededFlag};
h.buildCallback=function(){var a=this;this.j={width:this.element.getAttribute("width"),height:this.element.getAttribute("height")};var b=Math.round(this.getResource().getUpgradeDelayMs());z().info("amp-a4a","upgradeDelay "+this.element.getAttribute("type")+": "+b);X(this,"upgradeDelay",{forced_delta:b});this.uiHandler=new AMP.AmpAdUIHandler(this);var c=nd(this.win);this.Sa=R(this.getAmpDoc()).whenFirstVisible().then(function(){a.getSigningServiceNames().forEach(function(a){c.loadKeyset(a)})});if(this.pa=
this.getA4aAnalyticsConfig())this.$a=tc(this.element,this.pa);this.isSinglePageStoryAd=this.element.hasAttribute("amp-story")};
h.renderOutsideViewport=function(){if(!this.ha&&this.win["3pla"])return X(this,"throttled3p"),!1;var a;var b=this.element.getAttribute("data-loading-strategy");null==b?a=null:"prefer-viewability-over-views"==b||""==b?a=1.25:(a="Value of data-loading-strategy should be a float number in range of [0, 3], but got "+b,b=y().assertNumber(parseFloat(b),a),y().assert(0<=b&&3>=b,a),a=b);var c=a;return null!==c?c:AMP.BaseElement.prototype.renderOutsideViewport.call(this)};h.isValidElement=function(){return!0};
h.getCreativeSize=function(){return this.j};h.delayAdRequestEnabled=function(){return!1};h.getPreconnectUrls=function(){return[]};h.getPrefetchUrls=function(){return[]};h.isAmpAdElement=function(){return"AMP-AD"==this.element.tagName||"AMP-EMBED"==this.element.tagName};h.preconnectCallback=function(){var a=this,b=this.getPreconnectUrls();b&&b.forEach(function(b){a.preconnect.url(b,!0)})};
h.resumeCallback=function(){if(!this.R){X(this,"resumeCallback");this.fromResumeCallback=!0;var a=this.getResource();if(a.hasBeenMeasured()&&!a.isMeasureRequested())this.onLayoutMeasure()}};h.getResource=function(){return this.element.getResources().getResourceForElement(this.element)};h.hasAdPromise=function(){return!!this.O};
function od(a){var b=a.getIntersectionElementLayoutBox();if("fluid"!=a.getLayout()&&(0==b.height||0==b.width))return!1;var b=a.win,c=!1,d=0,e=a.element;do{if(uc[e.tagName])d++,c=!1;else{var f=(b.getComputedStyle(e)||ka()).position;"fixed"!=f&&"sticky"!=f||(c=!0)}e=e.parentElement}while(e&&"BODY"!=e.tagName);return!c&&1>=d?a.isValidElement()?!0:(y().warn("amp-a4a",a.element.getAttribute("type"),"Amp ad element ignored as invalid",a.element),!1):(y().warn("amp-a4a","<"+a.element.tagName+"> is not allowed to be "+
("placed in elements with position:fixed: "+a.element)),!1)}h.onLayoutMeasure=function(){this.initiateAdRequest()};
h.initiateAdRequest=function(){var a=this;if(this.J)this.J.onLayoutMeasure();if(!this.O&&od(this)){++this.$;var b=this.verifyStillCurrent();this.O=R(this.getAmpDoc()).whenFirstVisible().then(function(){b();if(a.delayAdRequestEnabled()&&!a.getResource().renderOutsideViewport())return a.getResource().whenWithinRenderOutsideViewport()}).then(function(){b();var c=AMP.BaseElement.prototype.getConsentPolicy.call(a);return c?vc(a.getAmpDoc(),c):Promise.resolve(null)}).then(function(c){b();return a.getAdUrl(c,
pd(a,c))}).then(function(c){b();a.D=c;X(a,"urlBuilt");return c&&a.sendXhrRequest(c)}).then(function(c){b();X(a,"adRequestEnd");if(!c||!c.arrayBuffer||c.headers.has("amp-ff-empty-creative"))return a.forceCollapse(),Promise.reject("NO-CONTENT-RESPONSE");c.headers&&c.headers.has("amp-ff-exps")&&qd(a,c.headers.get("amp-ff-exps"));var d=a.getNonAmpCreativeRenderingMethod(c.headers.get("X-AmpAdRender"));a.V=d;"nameframe"==a.V&&a.preconnect.preload(wc(a.win));var e=a.win.HTMLIFrameElement&&"sandbox"in a.win.HTMLIFrameElement.prototype;
a.Wa=e&&"true"==c.headers.get("amp-ff-sandbox");var f=c.headers.get("X-AmpSafeFrameVersion");/^[0-9-]+$/.test(f)&&"1-0-23"!=f&&(a.safeframeVersion=f,a.preconnect.preload(a.getSafeframePath()));return c.arrayBuffer().then(function(b){return 0==b.byteLength?(a.forceCollapse(),Promise.reject("NO-CONTENT-RESPONSE")):{bytes:b,headers:c.headers}})}).then(function(c){b();if(!c)return Promise.resolve();var d=c,e=d.bytes,d=d.headers,f=a.extractSize(c.headers);a.j=f||a.j;"client_cache"!=a.V&&e&&(a.ca=e);return a.maybeValidateAmpCreative(e,
d)}).then(function(c){b();a.ha=!!c;return c&&nc(c)}).then(function(c){b();var d;if(!c||!(d=a.getAmpAdMetadata(c)))return null;a.updateLayoutPriority(0);var e=gb(a.win);d.customElementExtensions.forEach(function(a){return e.preloadExtension(a)});(d.customStylesheets||[]).forEach(function(b){return a.preconnect.preload(b.href)});(d.images||[]).forEach(function(b){return F(b)&&a.preconnect.preload(b)});return d}).catch(function(b){switch(b.message||b){case "NETWORK-FAILURE":return null;case "INVALID-SPSA-RESPONSE":case "NO-CONTENT-RESPONSE":return{minifiedCreative:"",
customElementExtensions:[],customStylesheets:[]}}rd(a,b);return null})}};
h.maybeValidateAmpCreative=function(a,b){var c=this;X(this,"adResponseValidateStart");var d=this.verifyStillCurrent();return this.Sa.then(function(){return"fake"!=c.element.getAttribute("type")||c.element.getAttribute("checksig")?nd(c.win).verify(a,b,function(a,b){X(c,a,b)}):Promise.resolve(0)}).then(function(b){d();X(c,"adResponseValidateEnd",{signatureValidationResult:b,releaseType:c.Da});var e=null;switch(b){case 0:e=a;break;case 4:e=c.shouldPreferentialRenderWithoutCrypto()?a:null;break;case 2:case 3:y().error("amp-a4a",
c.element.getAttribute("type"),"Signature verification failed")}if(c.isSinglePageStoryAd&&!e)throw Error("INVALID-SPSA-RESPONSE");return e})};function qd(a,b){b.split(",").forEach(function(b){if(b){var c=b.split("=");2==c.length&&c[0]?a.postAdResponseExperimentFeatures[c[0]]=c[1]:z().warn("amp-a4a","invalid experiment feature "+b)}})}
h.refresh=function(a){var b=this;this.isRefreshing=!0;this.tearDownSlot();this.initiateAdRequest();var c=this.$;return this.O.then(function(){if(b.isRefreshing&&c==b.$)return b.mutateElement(function(){b.togglePlaceholder(!0);return Q(b.win).promise(1E3).then(function(){b.isRelayoutNeededFlag=!0;b.getResource().layoutCanceled();ib(b.getAmpDoc()).requireLayout(b.element)})});a()})};
function rd(a,b){var c;if(cc(b))throw b;b=b&&b.message?ga(b):Error("unknown error "+b);c&&(b.ignoreStack=c);var d=a.element.getAttribute("type")||"notype";0!=b.message.indexOf("amp-a4a: "+d+":")&&(b.message="amp-a4a: "+d+": "+b.message);sd(b,a.D);r().development||r().log?y().error("amp-a4a",b):(y().warn("amp-a4a",b),.01>Math.random()&&z().expectedError("amp-a4a",b))}h.layoutCallback=function(){this.isRefreshing&&this.destroyFrame(!0);return this.attemptToRenderCreative()};
h.attemptToRenderCreative=function(){var a=this;if(!this.O)return od(this)&&z().error("amp-a4a","Null promise in layoutCallback"),Promise.resolve();X(this,"preAdThrottle");var b=this.X(),c=this.verifyStillCurrent();return this.O.then(function(d){c();var e=a.X()-b;X(a,"layoutAdPromiseDelay",{layoutAdPromiseDelay:Math.round(e),isAmpCreative:!!d});return a.Y?Promise.resolve():a.iframe&&!a.isRefreshing?(X(a,"iframeAlreadyExists"),Promise.resolve()):d?td(a,d).catch(function(b){c();y().warn("amp-a4a",a.element.getAttribute("type"),
"Error injecting creative in friendly frame",b);return a.renderNonAmpCreative()}):a.renderNonAmpCreative()}).catch(function(b){rd(a,b);throw Error("CANCELLED");})};h.attemptChangeSize=function(a,b){this.N=this.N||this.getLayoutBox();return AMP.BaseElement.prototype.attemptChangeSize.call(this,a,b)};h.unlayoutCallback=function(){this.tearDownSlot();return!0};
h.tearDownSlot=function(){var a=this;this.$++;X(this,"adSlotCleared");this.uiHandler.applyUnlayoutUI();this.N&&AMP.BaseElement.prototype.attemptChangeSize.call(this,this.N.height,this.N.width).then(function(){a.N=null}).catch(function(a){z().warn("amp-a4a","unable to revert to original size",a)});this.Y=!1;this.destroyFrame();this.ca=this.D=this.O=null;this.fromResumeCallback=this.ha=!1;this.V=this.getNonAmpCreativeRenderingMethod();this.postAdResponseExperimentFeatures={}};
h.destroyFrame=function(a){if((a=void 0===a?!1:a)||!this.isRefreshing)this.iframe&&this.iframe.parentElement&&(this.iframe.parentElement.removeChild(this.iframe),this.iframe=null),this.J&&(this.J.freeXOriginIframe(),this.J=null),this.R&&(this.R.destroy(),this.R=null)};h.viewportCallback=function(a){this.R&&Kc(this.R,a);this.J&&this.J.viewportCallback(a)};h.createPlaceholderCallback=function(){return this.uiHandler.createPlaceholder()};
h.getAdUrl=function(){throw Error("getAdUrl not implemented!");};h.resetAdUrl=function(){this.D=null};h.verifyStillCurrent=function(){var a=this,b=this.$;return function(){if(b!=a.$)throw Error("CANCELLED");}};h.extractSize=function(a){a=a.get("X-CreativeSize");if(!a)return null;var b=/^([0-9]+)x([0-9]+)$/.exec(a);return b?{width:Number(b[1]),height:Number(b[2])}:(y().error("amp-a4a","Invalid size header: "+a),null)};
h.forceCollapse=function(){this.isRefreshing?this.isRefreshing=!1:(this.N=this.N||this.getLayoutBox(),this.uiHandler.applyNoContentUI(),this.Y=!0)};h.onCreativeRender=function(a){var b=a?"renderFriendlyEnd":"renderCrossDomainEnd";X(this,b)};h.onCrossDomainIframeCreated=function(a){z().info("amp-a4a",this.element.getAttribute("type"),"onCrossDomainIframeCreated "+a)};
h.sendXhrRequest=function(a){var b=this;X(this,"adRequestStart");var c={mode:"cors",method:"GET",credentials:"include"};return M(this.win,"xhr").fetch(a,c).catch(function(a){if(a.response&&200<a.response.status)return null;X(b,"networkError");var c=b.onNetworkFailure(a,b.D);if(c.frameGetDisabled)z().info("amp-a4a","frame get disabled as part of network failure handler"),b.resetAdUrl();else return b.D=c.adUrl||b.D,Promise.reject("NETWORK-FAILURE");return null})};h.onNetworkFailure=function(){return{}};
h.getSigningServiceNames=function(){return["google"]};
h.renderNonAmpCreative=function(a){var b=this;if("true"==this.element.getAttribute("disable3pfallback"))return y().warn("amp-a4a",this.element.getAttribute("type"),"fallback to 3p disabled"),Promise.resolve(!1);z().warn("amp-a4a","fallback to 3p");var c=this.V,d=Promise.resolve(!1);"safeframe"!=c&&"nameframe"!=c||!this.ca?this.D?(za(this.D,this.element),d=ud(this,this.D)):y().warn("amp-a4a",this.element.getAttribute("type"),"No creative or URL available -- A4A can't render any ad"):(d=vd(this,this.ca),
this.ca=null);a||Bc(this.win,d);return d.then(function(a){X(b,"crossDomainIframeLoaded");return a})};
function td(a,b){X(a,"renderFriendlyStart");a.iframe=Ya(a.element.ownerDocument,"iframe",A({height:a.j.height,width:a.j.width,frameborder:"0",allowfullscreen:"",allowtransparency:"",scrolling:"no"}));a.applyFillContent(a.iframe);var c=[];b.customStylesheets&&b.customStylesheets.forEach(function(a){(a=a.href)&&c.push(a)});var d=a.verifyStillCurrent();return Lc(a.iframe,a.element,{host:a.element,url:a.D,html:b.minifiedCreative,extensionIds:b.customElementExtensions||[],fonts:c},function(b){var c=a.getAmpDoc(),
d=new kc(a.getAmpDoc(),b);Ka(b,new Xc(c,d))}).then(function(c){d();a.R=c;Jc(c,a.isInViewport());var e=c.iframe.contentDocument||c.win.document;Vb(e.body,"visibility","visible");dc(c.win,"navigationStart","loadEventEnd").then(function(b){d();X(a,"friendlyIframeLoaded",{"navStartToLoadEndDelta.AD_SLOT_ID":Math.round(b)})}).catch(function(b){z().error("amp-a4a",a.element.getAttribute("type"),"getTimingDataAsync for renderFriendlyEnd failed: ",b)});fd(a.onCreativeRender,a,function(b){z().error("amp-a4a",
a.element.getAttribute("type"),"Error executing onCreativeRender",b)})(b);return c.whenIniLoaded()}).then(function(){d();X(a,"friendlyIframeIniLoad")})}
function wd(a,b){var c=Object.assign(b,A({height:a.j.height,width:a.j.width}));a.sentinel&&(c["data-amp-3p-sentinel"]=a.sentinel);a.Wa&&(c.sandbox="allow-forms allow-pointer-lock allow-popups allow-popups-to-escape-sandbox allow-same-origin allow-scripts allow-top-navigation-by-user-activation");G(a.win,"no-sync-xhr-in-ads")&&(c.allow="sync-xhr 'none';");a.iframe=Ya(a.element.ownerDocument,"iframe",Object.assign(c,cd));a.J=new AMP.AmpAdXOriginIframeHandler(a);var d=a.J.init(a.iframe,!0);fd(a.onCreativeRender,
a,function(b){z().error("amp-a4a",a.element.getAttribute("type"),"Error executing onCreativeRender",b)})(null);return d}function ud(a,b){X(a,"renderCrossDomainStart",{isAmpCreative:a.ha,releaseType:a.Da});return wd(a,A({src:M(a.win,"xhr").getCorsUrl(a.win,b),name:JSON.stringify(sc(a.win,a.element,a.sentinel))}))}
function vd(a,b){var c=a.V;X(a,"renderSafeFrameStart",{isAmpCreative:a.ha,releaseType:a.Da});var d=a.verifyStillCurrent();return Ia(function(){return nc(b)}).then(function(b){d();var e,g="";switch(c){case "safeframe":e=a.getSafeframePath()+"?n=0";break;case "nameframe":e=wc(a.win);break;default:return y().error("A4A","A4A received unrecognized cross-domain name attribute iframe rendering mode request: %s.  Unable to render a creative for slot %s.",c,a.element.getAttribute("id")),Promise.reject("Unrecognized rendering mode request")}var k=
sc(a.win,a.element,a.sentinel,a.getAdditionalContextMetadata("safeframe"==c));"nameframe"==c?(k.creative=b,g=JSON.stringify(k)):"safeframe"==c&&(k=JSON.stringify(k),g=a.safeframeVersion+";"+b.length+";"+b+(""+k));return wd(a,A({src:e,name:g}))})}
h.getAmpAdMetadata=function(a){for(var b=-1,c,d=0;d<ad.length&&!(c=ad[d],b=a.lastIndexOf(c),0<=b);d++);if(0>b)return z().warn("amp-a4a",this.element.getAttribute("type"),"Could not locate start index for amp meta data in: %s",a),null;var e=a.lastIndexOf("\x3c/script>");if(0>e)return z().warn("amp-a4a",this.element.getAttribute("type"),"Could not locate closing script tag for amp meta data in: %s",a),null;try{var f=JSON.parse(a.slice(b+c.length,e)),g=f.ampRuntimeUtf16CharOffsets;if(!Array.isArray(g)||
2!=g.length||"number"!==typeof g[0]||"number"!==typeof g[1])throw Error("Invalid runtime offsets");var k={};if(f.customElementExtensions){if(k.customElementExtensions=f.customElementExtensions,!Array.isArray(k.customElementExtensions))throw Error("Invalid extensions",k.customElementExtensions);}else k.customElementExtensions=[];if(f.customStylesheets){k.customStylesheets=f.customStylesheets;var l="Invalid custom stylesheets";if(!Array.isArray(k.customStylesheets))throw Error(l);k.customStylesheets.forEach(function(a){if(!w(a)||
!a.href||"string"!==typeof a.href||!F(a.href))throw Error(l);})}Array.isArray(f.images)&&(k.images=f.images.splice(0,5));if(this.isSinglePageStoryAd){if(!f.ctaUrl||!f.ctaType)throw Error("INVALID-SPSA-RESPONSE");this.element.setAttribute("data-vars-ctatype",f.ctaType);this.element.setAttribute("data-vars-ctaurl",f.ctaUrl)}k.minifiedCreative=a.slice(0,g[0])+a.slice(g[1],b)+a.slice(e+9);return k}catch(m){z().warn("amp-a4a",this.element.getAttribute("type"),"Invalid amp metadata: %s",a.slice(b+c.length,
e));if(this.isSinglePageStoryAd)throw m;return null}};h.getSafeframePath=function(){return"https://tpc.googlesyndication.com/safeframe/"+(this.safeframeVersion+"/html/container.html")};h.collapsedCallback=function(){X(this,"adSlotCollapsed")};function X(a,b,c){if(a.pa){var d=ed[b];if(d){var e=Object.assign({time:Math.round(a.X())},a.getA4aAnalyticsVars(d));Xb(a.element,d,e)}}a.jb(b,c)}h.getA4aAnalyticsVars=function(){return{}};h.getA4aAnalyticsConfig=function(){return null};h.emitLifecycleEvent=function(){};
function pd(a,b){if(AMP.maybeExecuteRealTimeConfig)try{return AMP.maybeExecuteRealTimeConfig(a,a.Pa(),b)}catch(c){y().error("amp-a4a","Could not perform Real Time Config.",c)}else a.element.getAttribute("rtc-config")&&y().error("amp-a4a","RTC not supported for ad network "+a.element.getAttribute("type"))}h.Pa=function(){return{}};h.shouldPreferentialRenderWithoutCrypto=function(){return!1};
h.getNonAmpCreativeRenderingMethod=function(a){if(a){var b;a:{for(b in bd)if(bd[b]===a){b=!0;break a}b=!1}if(b)return a;z().error("AMP-A4A","cross-origin render mode header "+a)}return M(this.win,"platform").isIos()?"nameframe":null};h.getAdditionalContextMetadata=function(){};function sd(a,b){if(!(!b||a.args&&a.args.au)){var c=b.indexOf("?");-1!=c&&((a.args||(a.args={})).au=b.substring(c+1,c+251))}}
function nd(a){return a.AMP_FAST_FETCH_SIGNATURE_VERIFIER_||(a.AMP_FAST_FETCH_SIGNATURE_VERIFIER_=new pc(a,Rb))};function xd(){this.P={}}h=xd.prototype;h.addPingsForVisibility=function(){};h.sendPing=function(){};h.setPingParameter=function(a,b){null!=a&&""!==a&&null!==b&&void 0!==b&&""!==b&&(this.P[a]=String(b))};h.setPingParameters=function(a){for(var b in a)a.hasOwnProperty(b)&&this.setPingParameter(b,a[b])};h.reset=function(){this.P={}};h.getInitTime=function(){};h.getDeltaTime=function(){};
function Y(a,b,c){this.P={};var d=this;this.ib=b.getAttribute("data-a4a-upgrade-type")?"a4a":"amp";this.nb=c;this.bb=ub(a,void 0,b);var e=ec(a,"navigationStart")||Date.now();this.sa="number"==typeof e?e:Number(e);this.getDeltaTime=a.performance&&a.performance.now?a.performance.now.bind(a.performance):function(){return Date.now()-d.sa};this.Ua="https://csi.gstatic.com/csi";this.qb=J(b);this.Ja=R(b)}aa(Y,xd);Y.prototype.setPingAddress=function(a){this.Ua=a};
Y.prototype.sendPing=function(a){var b=dd[a]||9999,c=isNaN(Number(this.P.forced_delta))?Math.round(this.getDeltaTime()):this.P.forced_delta;delete this.P.forced_delta;var d=ya(this.P);""!=d&&(d=this.qb.expandStringSync(d,{AD_SLOT_NAMESPACE:this.ib,AD_SLOT_ID:this.nb,AD_SLOT_TIME_TO_EVENT:c,AD_SLOT_EVENT_NAME:a,AD_SLOT_EVENT_ID:b,AD_PAGE_CORRELATOR:this.bb,AD_PAGE_VISIBLE:this.Ja.isVisible()?1:0,AD_PAGE_FIRST_VISIBLE_TIME:Math.round(this.Ja.getFirstVisibleTime()-this.sa),AD_PAGE_LAST_VISIBLE_TIME:Math.round(this.Ja.getLastVisibleTime()-
this.sa)}));if(a=d?this.Ua+"?"+d:"")(new Image).src=a,z().info("PING",a)};Y.prototype.getInitTime=function(){return this.sa};
Y.prototype.addPingsForVisibility=function(a){var b=this;fb(a).then(function(c){var d=a.signals(),e=Promise.race([d.whenSignal("ini-load"),d.whenSignal("load-end")]),f=c.getAnalyticsRoot(a).getVisibilityManager();f.listenElement(a,{visiblePercentageMin:50},null,null,function(){b.sendPing("visHalf")});f.listenElement(a,{visiblePercentageMin:50},e,null,function(){b.sendPing("visHalfIniLoad")});f.listenElement(a,{visiblePercentageMin:1},null,null,function(){b.sendPing("firstVisible")});e.then(function(){b.sendPing("iniLoad")});
f.listenElement(a,{waitFor:"ini-load"},e,null,function(){b.sendPing("visIniLoad")});f.listenElement(a,{visiblePercentageMin:1,waitFor:"ini-load",totalTimeMin:1E3},e,null,function(){b.sendPing("visLoadAndOneSec")})})};var yd={a4aProfilingRate:{isTrafficEligible:function(){return!0},branches:["unused","unused"]}};function zd(a,b,c){function d(a,b){for(var d=/([^\n]*)(\n)?/g,f;(f=d.exec(a))&&(e+=f[1],f[2]&&(c(e,b&&d.lastIndex===a.length),e=""),d.lastIndex!==a.length););}var e="";if(b.body&&a.TextDecoder){var f=new TextDecoder("utf-8"),g=b.body.getReader();g.read().then(function l(a){a.value&&d(f.decode(a.value,{stream:!0}),a.done);a.done||g.read().then(l)})}else b.text().then(function(a){return d(a,!0)})}
function Ad(a){var b;return function(c,d){if(b){var e=S(b)||{},f=Object.keys(e).reduce(function(a,b){a[b.toLowerCase()]=e[b];return a},{});a(Bd(c),f,d);b=null}else b=c}}function Bd(a){return a.replace(/\\(n|r|\\)/g,function(a,c){return"n"==c?"\n":"r"==c?"\r":"\\"})};function Cd(a,b,c,d,e){e=void 0===e?!1:e;for(var f=[],g=a.split(","),k={},l=0;l<g.length;k={minWidth:k.minWidth,minHeight:k.minHeight},l++){var m=g[l],n=m.split("x");if(2!=n.length)y().error("AMP-AD","Invalid multi-size data format '"+m+"'.");else{var p=Number(n[0]),n=Number(n[1]);if(Dd(p,n,function(a){return isNaN(a)||0>=a},function(a){return isNaN(a)||0>=a},function(a){return a.map(function(a){return"Invalid "+a.dim+" of "+a.val+" given for secondary size."}).join(" ")})&&(e||Dd(p,n,function(a){return a>
b},function(a){return a>c},function(a){return a.map(function(a){return"Secondary "+a.dim+" "+a.val+" "+("can't be larger than the primary "+a.dim+".")}).join(" ")}))){if(d){var t=2/3;k.minWidth=t*b;k.minHeight=t*c;if(!Dd(p,n,function(a){return function(b){return b<a.minWidth}}(k),function(a){return function(b){return b<a.minHeight}}(k),function(a){return a.map(function(a){return"Secondary "+a.dim+" "+a.val+" is "+("smaller than 2/3rds of the primary "+a.dim+".")}).join(" ")}))continue}f.push([p,n])}}}return f}
function Dd(a,b,c,d,e){var f=[];c(a)&&f.push({dim:"width",val:a});d(b)&&f.push({dim:"height",val:b});f.length&&y().warn("AMP-AD",e(f));return!f.length};function Ed(a,b){var c=1E3;function d(d){g=null;f=a.setTimeout(e,c);b.apply(null,d)}function e(){f=0;g&&d(g)}var f=0,g=null;return function(a){for(var b=[],c=0;c<arguments.length;++c)b[c-0]=arguments[c];f?g=b:d(b)}};var Fd={medianet:{url:"https://amprtc.media.net/rtb/getrtc?cid=CID&w=ATTR(width)&h=ATTR(height)&ow=ATTR(data-override-width)&oh=ATTR(data-override-height)&ms=ATTR(data-multi-size)&slot=ATTR(data-slot)&tgt=TGT&curl=CANONICAL_URL&to=TIMEOUT&purl=HREF",macros:["CID"],disableKeyAppend:!0},prebidappnexus:{url:"https://prebid.adnxs.com/pbs/v1/openrtb2/amp?tag_id=PLACEMENT_ID&w=ATTR(width)&h=ATTR(height)&ow=ATTR(data-override-width)&oh=ATTR(data-override-height)&slot=ATTR(data-slot)&targeting=TGT&curl=CANONICAL_URL&timeout=TIMEOUT&adcid=ADCID&purl=HREF",
macros:["PLACEMENT_ID"],disableKeyAppend:!0},prebidrubicon:{url:"https://prebid-server.rubiconproject.com/openrtb2/amp?tag_id=REQUEST_ID&w=ATTR(width)&h=ATTR(height)&ow=ATTR(data-override-width)&oh=ATTR(data-override-height)&ms=ATTR(data-multi-size)&slot=ATTR(data-slot)&targeting=TGT&curl=CANONICAL_URL&timeout=TIMEOUT&adc=ADCID&purl=HREF",macros:["REQUEST_ID"],disableKeyAppend:!0},indexexchange:{url:"https://amp.casalemedia.com/amprtc?v=1&w=ATTR(width)&h=ATTR(height)&ow=ATTR(data-override-width)&oh=ATTR(data-override-height)&ms=ATTR(data-multi-size)&s=SITE_ID&p=CANONICAL_URL",
macros:["SITE_ID"],disableKeyAppend:!0},lotame:{url:"https://ad.crwdcntrl.net/5/pe=y/c=CLIENT_ID/an=AD_NETWORK",macros:["CLIENT_ID","AD_NETWORK"]},yieldbot:{url:"https://i.yldbt.com/m/YB_PSN/v1/amp/init?curl=CANONICAL_URL&sn=YB_SLOT&w=ATTR(width)&h=ATTR(height)&ow=ATTR(data-override-width)&oh=ATTR(data-override-height)&ms=ATTR(data-multi-size)&aup=ATTR(data-slot)&pvi=PAGEVIEWID&tgt=TGT&adcid=ADCID&href=HREF",macros:["YB_PSN","YB_SLOT"],disableKeyAppend:!0},salesforcedmp:{url:"https://cdn.krxd.net/userdata/v2/amp/ORGANIZATION_ID?segments_key=SEGMENTS_KEY&kuid_key=USER_KEY",
macros:["ORGANIZATION_ID","SEGMENTS_KEY","USER_KEY"],disableKeyAppend:!0},purch:{url:"https://ads.servebom.com/tmntag.js?v=1.2&fmt=amp&o={%22p%22%3APLACEMENT_ID}&div_id=DIV_ID",macros:["PLACEMENT_ID","DIV_ID"],disableKeyAppend:!0}};var Gd=.01>Math.random();function Z(a,b,c,d,e,f){z().warn("real-time-config","RTC callout to "+b+" caused "+a);if(c){var g=c;if(Gd)if(F(g)){var k={ERROR_TYPE:a,HREF:d.location.href};e=J(e).expandUrlSync(g,k,{ERROR_TYPE:!0,HREF:!0});(new d.Image).src=e}else z().warn("real-time-config","Insecure RTC errorReportingUrl: "+g)}return Promise.resolve({error:a,callout:b,rtcTime:f||0})}function Hd(a){a=C(a);return(a.hostname+a.pathname).substr(0,50)}
function Id(a,b,c,d,e,f,g,k,l){function m(a){if(5==Object.keys(c).length)return Z("7",t,k,n,p);if(!F(a))return Z("6",t,k,n,p);if(c[a])return Z("5",t,k,n,p);c[a]=!0;16384<a.length&&(a=a.substr(0,16372).replace(/%\w?$/,""),a+="&__trunc__=1");return Jd(a,e,n,g,t,v,k,p)}var n=a.win,p=a.getAmpDoc(),t=l||Hd(b),v=a.verifyStillCurrent.bind(a)(),u=J(p),B={};Object.keys(f).forEach(function(a){return B[a]=!0});var E=Date.now();d.push(Q(n).timeoutPromise(g,u.expandUrlAsync(b,f,B)).then(function(a){v();g-=E-Date.now();
return m(a)}).catch(function(a){return"CANCELLED"==a.message?void 0:Z("11",t,k,n,p)}))}function Jd(a,b,c,d,e,f,g,k){return Q(c).timeoutPromise(d,M(c,"xhr").fetchJson(a,{credentials:"include"}).then(function(a){f();return a.text().then(function(a){f();var d=Date.now()-b;return a?(a=S(a))?{response:a,rtcTime:d,callout:e}:Z("4",e,g,c,k,d):{rtcTime:d,callout:e}})})).catch(function(a){return"CANCELLED"==a.message?void 0:Z(a.message&&a.message.match(/^timeout/)?"10":"8",e,g,c,k,Date.now()-b)})}
function Kd(a){var b=1E3,c=a.getAttribute("rtc-config");if(!c)return null;var d=S(c);if(!d)return y().warn("real-time-config","Could not parse rtc-config attribute"),null;var e;try{if(y().assert(d.vendors||d.urls,"RTC Config must specify vendors or urls"),Object.keys(d).forEach(function(a){switch(a){case "vendors":y().assert(w(d[a]),"RTC invalid vendors");break;case "urls":y().assert(Array.isArray(d[a]),"RTC invalid urls");break;case "timeoutMillis":e=parseInt(d[a],10);if(isNaN(e))y().warn("real-time-config",
"Invalid RTC timeout is NaN, "+("using default timeout "+b+"ms")),e=void 0;else if(e>=b||0>e)y().warn("real-time-config","Invalid RTC timeout: "+e+"ms, "+("using default timeout "+b+"ms")),e=void 0;break;default:y().warn("real-time-config","Unknown RTC Config key: "+a)}}),!Object.keys(d.vendors||{}).length&&!(d.urls||[]).length)return null}catch(f){return null}d.timeoutMillis=void 0!==e?e:b;return d}
AMP.maybeExecuteRealTimeConfig=function(a,b,c){if(2!=c&&0!=c){var d=Kd(a.element);if(d){b.TIMEOUT=function(){return d.timeoutMillis};var e=[],f={},g=Date.now();(d.urls||[]).forEach(function(c){var k,m;w(c)?(k=c.url,m=c.errorReportingUrl):"string"==typeof c?k=c:z().warn("real-time-config","Invalid url: "+c);Id(a,k,f,e,g,b,d.timeoutMillis,m)});Object.keys(d.vendors||[]).forEach(function(c){var k=Fd[c.toLowerCase()],m=k?k.url:"",n=k?k.errorReportingUrl:"";if(!m)return e.push(Z("9",c,n,a.win,a.getAmpDoc()));
var p={};Object.keys(d.vendors[c]).forEach(function(a){if(k.macros&&k.macros.includes(a)){var b=d.vendors[c][a];p[a]=w(b)||Array.isArray(b)?JSON.stringify(b):b}else y().warn("real-time-config","Unknown macro: "+a+" for vendor: "+c)});var t=Object.assign(p,b);Id(a,m,f,e,g,t,d.timeoutMillis,n,c.toLowerCase())});return Promise.all(e)}}};var Ld=Date.now();function Md(a,b){this.Ma=a;var c=b&&b.threshold,c=c?Array.isArray(c)?c:[c]:[0];for(a=0;a<c.length;a++)fa(c[a]);this.pb=c.sort();this.Ca=null;this.Ta=void 0;this.H=[]}Md.prototype.disconnect=function(){this.H.length=0};Md.prototype.observe=function(a){for(var b=0;b<this.H.length;b++)if(this.H[b].element===a){z().warn("INTERSECTION-OBSERVER","should observe same element once");return}var c={element:a,currentThresholdSlot:0};this.Ca&&(a=Nd(this,c,this.Ca,this.Ta))&&this.Ma([a]);this.H.push(c)};
Md.prototype.unobserve=function(a){for(var b=0;b<this.H.length;b++)if(this.H[b].element===a){this.H.splice(b,1);return}z().warn("INTERSECTION-OBSERVER","unobserve non-observed element")};Md.prototype.tick=function(a,b){b&&(a=Gc(a,-b.left,-b.top),b=Gc(b,-b.left,-b.top));this.Ca=a;this.Ta=b;for(var c=[],d=0;d<this.H.length;d++){var e=Nd(this,this.H[d],a,b);e&&c.push(e)}c.length&&this.Ma(c)};
function Nd(a,b,c,d){var e=b.element,f=null,g=e.getLayoutBox(),k=e.getOwner(),f=k&&k.getLayoutBox(),l=Fc(g,f,c,d)||Ec(0,0,0,0),k=l,m=g,k=k.width*k.height/(m.width*m.height);a=a.pb;var m=0,n=a.length;if(0==k)a=0;else{for(var p=(m+n)/2|0;m<p;)k<a[p]?n=p:m=p,p=(m+n)/2|0;a=n}var t=a;if(t==b.currentThresholdSlot)return null;b.currentThresholdSlot=t;c=d?null:c;d=l;a=g;if(m=c)d=Gc(d,-c.left,-c.top),a=Gc(a,-c.left,-c.top),m=Gc(m,-c.left,-c.top);var v={time:"undefined"!==typeof performance&&performance.now?
performance.now():Date.now()-Ld,rootBounds:m,boundingClientRect:a,intersectionRect:d,intersectionRatio:k,target:e};return v};function Od(a,b,c){this.va=new Md(a,c);this.Ya={};this.w=b.getViewport();this.Ha=!1}Od.prototype.observe=function(a){var b=this,c=a.getAttribute("data-amp-ad-refresh-id");if(!this.Ya[c]){var d=a.viewportCallback.bind(a);this.Ya[c]=d;a.viewportCallback=function(a){b.Ha&&b.va.tick(b.w.getRect());d(a)}}this.Ha=!0;this.va.observe(a)};Od.prototype.unobserve=function(a){this.va.tick(this.w.getRect());this.va.unobserve(a);this.Ha=!1};function Pd(a,b){var c=a.getAttribute("data-enable-refresh");if(c)return Qd(c);var d,e=(d=b.document.getElementsByName("amp-ad-enable-refresh"))&&d[0]&&d[0].getAttribute("content");if(!e)return null;var f=e.split(",");for(b=0;b<f.length;b++){var g=f[b].split("=");y().assert(2==g.length,"refresh metadata config must be of the form `network_type=refresh_interval`");if(g[0].toLowerCase()==a.getAttribute("type").toLowerCase())return Qd(g[1])}return null}
function Qd(a){var b=Number(a);return isNaN(b)||30>b?(y().warn("AMP-AD","invalid refresh interval, must be a number no less than 30: "+a),null):1E3*b}var Rd={},Sd={},Td=0;function Ud(a,b){var c=Pd(a.element,a.win);return!c||b&&!b()?null:new Vd(a,{visiblePercentageMin:50,continuousTimeMin:1},c)}
function Vd(a,b,c){this.aa="initial";this.La=a;this.m=a.win;this.ea=a.element;this.sb=this.ea.getAttribute("type").toLowerCase();this.kb=c;b.continuousTimeMin*=1E3;b.visiblePercentageMin/=100;this.ba=b;this.Ea=Q(this.m);this.Ka=this.lb=null;var d=String(Td++);this.ea.setAttribute("data-amp-ad-refresh-id",d);Sd[d]=this;this.initiateRefreshCycle()}
function Wd(a,b){var c=String(b);return Rd[c]||(Rd[c]="IntersectionObserver"in a.m?new a.m.IntersectionObserver(a.Ra,{threshold:b}):new Od(a.Ra,a.La,{threshold:b}))}
Vd.prototype.Ra=function(a){a.forEach(function(a){var b=a.target.getAttribute("data-amp-ad-refresh-id"),d=Sd[b];if(a.target==d.ea)switch(d.aa){case "initial":a.intersectionRatio>=d.ba.visiblePercentageMin&&(d.aa="view_pending",d.Ka=d.Ea.delay(function(){d.aa="refresh_pending";Xd(d)},d.ba.continuousTimeMin));break;case "view_pending":a.intersectionRatio<d.ba.visiblePercentageMin&&(d.Ea.cancel(d.Ka),d.Ka=null,d.aa="initial")}})};
Vd.prototype.initiateRefreshCycle=function(){switch(this.aa){case "initial":Wd(this,this.ba.visiblePercentageMin).observe(this.ea)}};function Xd(a){new Promise(function(b){a.lb=a.Ea.delay(function(){a.aa="initial";a.unobserve();a.La.refresh(function(){return a.initiateRefreshCycle()});b(!0)},a.kb)})}Vd.prototype.unobserve=function(){Wd(this,this.ba.visiblePercentageMin).unobserve(this.ea)};function Yd(a,b){b.document.documentElement.addEventListener("click",Zd.bind(null,a),!0)}function Zd(a,b){var c=$a(b.target);if(c&&c.href){var d=c.getAttribute("data-a4a-orig-href")||c.getAttribute("href");d&&(a=J(a).expandUrlSync(d,{CLICK_X:function(){return b.pageX},CLICK_Y:function(){return b.pageY}},void 0,{CLICK_X:!0,CLICK_Y:!0}),a!=d&&(c.getAttribute("data-a4a-orig-href")||c.setAttribute("data-a4a-orig-href",d),c.setAttribute("href",a)))}};var $d={},ae=!1;function be(a){var b=S(a.data);if("https://tpc.googlesyndication.com"==a.origin&&b){a=S(b.p)||{};var c=b.e||a.sentinel,d=$d[c];d?d.channel?a&&d.processMessage(a,b.s):d.connectMessagingChannel(b.c):z().warn("AMP-DOUBLECLICK-SAFEFRAME","Safeframe Host for sentinel: "+c+" not found.")}}
function ce(a,b,c,d){this.l=a;this.ra=this.l.verifyStillCurrent.bind(this.l)();this.m=this.l.win;this.ma=this.l.sentinel;this.da=this.channel=this.B=null;this.cb=Math.random();this.Fa=Math.random();this.o=b;this.j=c;this.ta=Object.assign({},c);this.W=d;this.tb=null;this.w=this.l.getViewport();this.Y=!0;this.xa=!1;var e=Object(S(this.l.element.getAttribute("data-safeframe-config"))||{});this.Na=e.hasOwnProperty("expandByOverlay")?e.expandByOverlay:!0;this.Oa=e.hasOwnProperty("expandByPush")?e.expandByPush:
!0;this.Ga=null;this.registerSafeframeHost()}h=ce.prototype;
h.getSafeframeNameAttr=function(){var a=A({});a.uid=this.Fa;a.hostPeerName=this.m.location.origin;a.initialGeometry=this.getInitialGeometry();a.permissions=JSON.stringify(A({expandByOverlay:this.Na,expandByPush:this.Oa,readCookie:!1,writeCookie:!1}));a.metadata=JSON.stringify(A({shared:{sf_ver:this.l.safeframeVersion,ck_on:1,flash_ver:"26.0.0",canonical_url:this.maybeGetCanonicalUrl(),amp:{canonical_url:this.maybeGetCanonicalUrl()}}}));a.reportCreativeGeometry=this.o;a.isDifferentSourceWindow=!1;
a.sentinel=this.ma;return a};h.maybeGetCanonicalUrl=function(){var a=P(this.l.getAmpDoc()).canonicalUrl,b=this.m.document.querySelector("meta[name='referrer']");if(!b)return a;switch(b.getAttribute("content")){case "same-origin":return;case "no-referrer":return;case "origin":return C(a).origin}return a};
h.getInitialGeometry=function(){var a=this.l.getPageLayoutBox(),b=(a.height-this.j.height)/2,c=(a.width-this.j.width)/2,d={top:a.top+b,bottom:a.bottom-b,left:a.left+c,right:a.right-c,height:this.ta.height,width:this.ta.width};return de(this,d)};h.registerSafeframeHost=function(){$d[this.ma]=$d[this.ma]||this;ae||(ae=!0,this.m.addEventListener("message",be,!1))};h.connectMessagingChannel=function(a){this.B=this.l.iframe;this.channel=a;ee(this);fe(this,{message:"connect",c:this.channel},"")};
function ee(a){var b=Ed(a.m,a.Xa.bind(a)),c=a.w.onScroll(b),d=a.w.onChanged(b);a.Ga=function(){c();d()};a.Xa()}h.Xa=function(){var a=this;this.B&&this.w.getClientRectAsync(this.B).then(function(b){a.ra();var c=de(a,b);fe(a,{newGeometry:c,uid:a.Fa},"geometry_update")}).catch(function(a){return z().error("AMP-DOUBLECLICK-SAFEFRAME",a)})};
function de(a,b){var c=a.w.getSize(),d=a.w.getScrollLeft(),e=a.w.getScrollTop(),f=c.width,g=c.height,k=b.top+e,l=b.right+d,m=b.bottom+e,n=b.left+d,p=b.top,t=b.bottom,v=b.right,u=b.left,B;B=a.l.element;var E=Ub(B.style,"zIndex",void 0);B=E?B.style[E]:void 0;var D={windowCoords_t:0,windowCoords_r:f,windowCoords_b:g,windowCoords_l:0,frameCoords_t:k,frameCoords_r:l,frameCoords_b:m,frameCoords_l:n,posCoords_t:p,posCoords_b:t,posCoords_r:v,posCoords_l:u,styleZIndex:B,allowedExpansion_r:c.width-b.width,
allowedExpansion_b:c.height-b.height,allowedExpansion_t:0,allowedExpansion_l:0,yInView:a.getPercInView(c.height,b.top,b.bottom),xInView:a.getPercInView(c.width,b.left,b.right)};a.da=D;return JSON.stringify(D)}h.getPercInView=function(a,b,c){var d=c>=a?a-b:c,e=d/(c-b);return Math.max(0,Math.min(1,e))||0};
function fe(a,b,c){if(a.B.contentWindow){var d={};d.c=a.channel;d.p=JSON.stringify(b);d.s=c;d.e=a.ma;d.i=a.cb;a.B.contentWindow.postMessage(JSON.stringify(d),"https://tpc.googlesyndication.com")}else z().error("AMP-DOUBLECLICK-SAFEFRAME","Frame contentWindow unavailable.")}
h.processMessage=function(a,b){switch(b){case "creative_geometry_update":ge(this,a);break;case "expand_request":if(this.xa){b=Number(this.j.height)+a.expand_b+a.expand_t;var c=Number(this.j.width)+a.expand_r+a.expand_l;isNaN(b)||isNaN(c)||a.push&&!this.Oa||!a.push&&!this.Na&&(c>this.j.width||b>this.j.height)?(z().error("AMP-DOUBLECLICK-SAFEFRAME","Invalid expand values."),this.sendResizeResponse(!1,"expand_response")):b>this.w.getSize().height||c>this.w.getSize().width?this.sendResizeResponse(!1,
"expand_response"):this.handleSizeChange(b,c,"expand_response")}break;case "register_done":this.xa=!0;break;case "collapse_request":this.Y||!this.xa?this.sendResizeResponse(!1,"collapse_response"):this.handleSizeChange(this.ta.height,this.ta.width,"collapse_response",!0);break;case "resize_request":this.xa&&(b=Number(this.j.height)+(a.resize_b+a.resize_t),a=Number(this.j.width)+(a.resize_r+a.resize_l),isNaN(a)||isNaN(b)||a>this.j.width||b>this.j.height?z().error("AMP-DOUBLECLICK-SAFEFRAME","Invalid resize values."):
this.resizeAmpAdAndSafeframe(b,a,"resize_response",!0))}};h.resizeSafeframe=function(a,b,c){var d=this;this.Y="collapse_response"==c;this.l.measureMutateElement(function(){d.l.getResource().measure()},function(){d.B&&(U(d.B,{height:a+"px",width:b+"px"}),d.j.height=a,d.j.width=b);d.sendResizeResponse(!0,c)},this.B)};
h.handleSizeChange=function(a,b,c,d){var e=this;return this.w.getClientRectAsync(this.l.element).then(function(f){!d&&b<=f.width&&a<=f.height?e.resizeSafeframe(a,b,c):e.resizeAmpAdAndSafeframe(a,b,c,d)})};
h.sendResizeResponse=function(a,b){var c=this;this.B&&this.w.getClientRectAsync(this.B).then(function(d){c.ra();d=de(c,d);fe(c,{uid:c.Fa,success:a,newGeometry:d,expand_t:c.da.allowedExpansion_t,expand_b:c.da.allowedExpansion_b,expand_r:c.da.allowedExpansion_r,expand_l:c.da.allowedExpansion_l,push:!0},b)}).catch(function(a){return z().error("AMP-DOUBLECLICK-SAFEFRAME",a)})};
h.resizeAmpAdAndSafeframe=function(a,b,c,d){var e=this;this.l.attemptChangeSize(a,b).then(function(){e.ra();e.resizeSafeframe(a,b,c)},function(){e.l.getResource().resetPendingChangeSize();d?e.resizeSafeframe(a,b,c):e.sendResizeResponse(!1,c)}).catch(function(a){"CANCELLED"==a.message?z().error("AMP-DOUBLECLICK-SAFEFRAME",a):(z().error("AMP-DOUBLECLICK-SAFEFRAME","Resizing failed: "+a),e.sendResizeResponse(!1,c))})};
function ge(a,b){var c;b&&(c=parseInt(b.height,10))?a.l.attemptChangeHeight(c).then(function(){a.ra();a.W&&(a.l.fireDelayedImpressions(a.W),a.W=null);a.B.contentWindow.postMessage(JSON.stringify(A({message:"resize-complete",c:a.channel})),"https://tpc.googlesyndication.com")}).catch(function(b){"CANCELLED"==b.message?z().error("AMP-DOUBLECLICK-SAFEFRAME",b):a.l.forceCollapse()}):a.l.forceCollapse()}
h.destroy=function(){this.B=null;delete $d[this.ma];this.Ga&&this.Ga();0==Object.keys($d).length&&(window.removeEventListener("message",be,!1),ae=!1)};var he=null,ie,me=[function(a){var b={},c=0,d=[];a.forEach(function(a){var e=a.element.getAttribute("data-slot"),g=(e||"").split("/"),k=[];for(a=0;a<g.length;a++)if(""!=g[a]){var l=b[g[a]];void 0==l&&(b[g[a]]=l=c++);k.push(l)}d.push(k.join("/"))});return{iu_parts:Object.keys(b).join(),enc_prev_ius:d.join()}},function(a){return je(a,function(a){return a.h&&a.h.cookieOptOut?{co:"1"}:null})},function(a){return{adks:a.map(function(a){return a.Aa}).join()}},function(a){return{prev_iu_szs:a.map(function(a){return a.Z}).join()}},
function(a){return je(a,function(a){return a.h&&a.h.tagForChildDirectedTreatment?{tfcd:a.h.tagForChildDirectedTreatment}:null})},function(a){return je(a,function(a){return Lb(a.element)?{adtest:"on"}:null})},function(a){var b=[];a.forEach(function(a){a.h&&b.push(ke(a.h.targeting||null,a.h.categoryExclusions||null))});return b.length?{prev_scp:b.join("|")}:null},function(a){var b={};a.forEach(function(a){var c=a.element.getAttribute("data-experiment-id");c&&c.split(",").forEach(function(a){return b[a]=
1});var e=/(?:#|,)deid=(\d+)/i.exec(a.win.location.hash);e&&(b[e[1]]=1)});return Object.keys(b).length?{eid:Object.keys(b).join()}:null},function(a){return je(a,function(a){return le(a)})},function(a){var b=!1,c=[];a.forEach(function(a){b=b||a.fa;c.push(Number(a.fa))});return b?{fsfs:c.join(",")}:null},function(a){return{adxs:a.map(function(a){return a.getPageLayoutBox().left}).join()}},function(a){return{adys:a.map(function(a){return a.getPageLayoutBox().top}).join()}},function(a){var b=!1,c=[];
a.forEach(function(a){a=ob(a.element);c.push(a.join());b=b||!!a.length});return b?{acts:c.join("|")}:null}];
function ne(a){a=W.call(this,a)||this;a.L=a.L||a.initLifecycleReporter();a.U=null;a.fb=gb(a.win);a.ia=null;a.S=null;a.Z=null;a.ya=null;a.qa=null;a.h=null;a.Aa=0;a.useSra=!!a.win.document.querySelector("meta[name=amp-ad-doubleclick-sra]")||Qb(a.win,"117152667");a.sraDeferred=new I;a.ja=null;a.Va=0;a.Ba=0;a.o=!1;a.W=null;a.Qa=null;a.identityToken=null;a.G={};a.ga=null;a.wa=!1;a.I=null;a.fa=!1;"forceSafeframe"in a.element.dataset&&(/^(1|(true))$/i.test(a.element.dataset.forceSafeframe)?a.fa=!0:y().warn("amp-ad-network-doubleclick-impl",
"Ignoring invalid data-force-safeframe attribute: "+a.element.dataset.forceSafeframe));a.consentState=null;return a}aa(ne,W);h=ne.prototype;h.idleRenderOutsideViewport=function(){var a=this;if(this.element.getAttribute("data-loading-strategy"))return!1;var b=this.postAdResponseExperimentFeatures["render-idle-vp"],c=parseInt(b,10);if(b&&isNaN(c))return!1;c=c||12;this.wa=!0;this.getResource().whenWithinRenderOutsideViewport().then(function(){return a.wa=!1});return c};
h.isLayoutSupported=function(a){return(this.o="fluid"==a)||lc(a)};h.isValidElement=function(){return this.isAmpAdElement()};h.delayAdRequestEnabled=function(){return Qb(this.win,"21060729")};
h.buildCallback=function(){var a=this;W.prototype.buildCallback.call(this);this.Qa=R(this.getAmpDoc()).whenFirstVisible().then(function(){var b=a.win,c=a.getAmpDoc();b.goog_identity_prom=b.goog_identity_prom||Gb(b,c);return b.goog_identity_prom});this.G.slotId=this.element.getAttribute("data-slot");this.G.slotIndex=this.element.getAttribute("data-amp-slot-index");if(this.win.dbclk_a4a_viz_change){var b=H(this.win,"dbclk-correlator-clear");b&&Nb(b,this.element)}else{this.win.dbclk_a4a_viz_change=!0;
var c=R(this.getAmpDoc());c.onVisibilityChanged(function(){if("paused"==c.getVisibilityState()&&!a.useSra&&a.win.ampAdPageCorrelator){Ea(a.win,{"dbclk-correlator-clear":{isTrafficEligible:function(){return!0},branches:["22302764","22302765"]}});var b=H(a.win,"dbclk-correlator-clear");b&&(Nb(b,a.element),"22302765"===b&&(z().info("amp-ad-network-doubleclick-impl","resetting page correlator"),a.win.ampAdPageCorrelator=null))}})}};
h.shouldPreferentialRenderWithoutCrypto=function(){Ib(this.win);return!Qb(this.win,"21061373","expUnconditionedCanonicalHoldback")};h.getPageParameters=function(a){return{npa:2==a||0==a?1:null,gdfp_req:"1",sfv:"1-0-23",u_sd:this.win.devicePixelRatio,gct:this.getLocationQueryParameterValue("google_preview")||null}};
function oe(a){var b=a.h&&a.h.tagForChildDirectedTreatment;a.win.ampAdGoogleIfiCounter=a.win.ampAdGoogleIfiCounter||1;a.Ba=a.isRefreshing&&a.Ba||a.win.ampAdGoogleIfiCounter++;var c=a.isSinglePageStoryAd?a.element.getPageLayoutBox():null;return Object.assign({iu:a.element.getAttribute("data-slot"),co:a.h&&a.h.cookieOptOut?"1":null,adk:a.Aa,sz:a.isSinglePageStoryAd?"1x1":a.Z,output:"html",impl:"ifr",tfcd:void 0==b?null:b,adtest:Lb(a.element)?"on":null,ifi:a.Ba,rc:a.Va||null,frc:Number(a.fromResumeCallback)||
null,fluid:a.o?"height":null,fsf:a.fa?"1":null,scp:ke(a.h&&a.h.targeting||null,a.h&&a.h.categoryExclusions||null),spsa:a.isSinglePageStoryAd?c.width+"x"+c.height:null},nb(a))}
h.populateAdUrlState=function(a){this.consentState=a;a=Number(this.element.getAttribute("data-override-width"))||Number(this.element.getAttribute("width"));var b=Number(this.element.getAttribute("data-override-height"))||Number(this.element.getAttribute("height"));this.S=this.o?{width:0,height:0}:a&&b?{width:a,height:b}:this.getIntersectionElementLayoutBox();this.h=S(this.element.getAttribute("json"))||{};this.Aa=pe(this,this.S.width+"x"+this.S.height);this.Z=this.o?"320x50":this.S.width+"x"+this.S.height;
if(a=this.element.getAttribute("data-multi-size"))"responsive"==this.element.getAttribute("layout")&&y().warn("amp-ad-network-doubleclick-impl","Behavior of multi-size and responsive layout is currently not well defined. Proceed with caution."),b=this.element.getAttribute("data-multi-size-validation")||"true",a=Cd(a,this.S.width,this.S.height,"true"==b,this.o),this.Z+="|"+a.map(function(a){return a.join("x")}).join("|")};h.getConsentPolicy=function(){return null};
h.getAdUrl=function(a,b){var c=this;if(0==a&&"true"!=this.element.getAttribute("data-npa-on-unknown-consent"))return y().info("amp-ad-network-doubleclick-impl","Ad request suppressed due to unknown consent"),Promise.resolve("");if(this.iframe&&!this.isRefreshing)return z().warn("amp-ad-network-doubleclick-impl","Frame already exists, sra: "+this.useSra),Promise.resolve("");b=b||Promise.resolve();this.populateAdUrlState(a);var d=Date.now(),e=Q(this.win).timeoutPromise(1E3,this.Qa).catch(function(){return{}}),
f=Promise.all([b,e]).then(function(b){c.verifyStillCurrent();var e=qe(c,b[0]);c.identityToken=b[1];return zb(c,d,Object.assign(oe(c),le(c),c.getPageParameters(a),e))});return this.G.adUrl=f};function le(a){return a.identityToken?{adsid:a.identityToken.token||null,jar:a.identityToken.jar||null,pucrd:a.identityToken.pucrd||null}:{}}
function qe(a,b){if(!b)return null;var c=[],d=[],e=[],f;b.forEach(function(b){c.push(b.rtcTime);d.push(b.error||"2");e.push(b.callout);if(b.response){if(b.response.targeting){var g=re(b.response.targeting,b.callout);a.h.targeting=a.h.targeting?la(a.h.targeting,g):g}b.response.categoryExclusions&&(f||(f={},a.h.categoryExclusions&&a.h.categoryExclusions.forEach(function(a){f[a]=!0})),b.response.categoryExclusions.forEach(function(a){f[a]=!0}))}});f&&(a.h.categoryExclusions=Object.keys(f));return{artc:c.join()||
null,ati:d.join(),ard:e.join()}}
h.Pa=function(){var a=this,b={height:!0,width:!0,"data-slot":!0,"data-multi-size":!0,"data-multi-size-validation":!0,"data-override-width":!0,"data-override-height":!0};return{PAGEVIEWID:function(){return P(a.element).pageViewId},HREF:function(){return a.win.location.href},REFERRER:function(b){return se(a,b)},TGT:function(){return JSON.stringify((S(a.element.getAttribute("json"))||{}).targeting)},ADCID:function(b){return jb(a.getAmpDoc(),parseInt(b,10))},ATTR:function(c){if(b[c.toLowerCase()])return a.element.getAttribute(c);z().warn("TAG",
"Invalid attribute "+c)},CANONICAL_URL:function(){return P(a.element).canonicalUrl}}};function se(a,b){var c=parseInt(b,10),d=R(a.getAmpDoc()).getReferrerUrl();return isNaN(c)||0>c?d:Q(a.win).timeoutPromise(c,d).catch(function(){})}function re(a,b){if(!Fd[b]||Fd[b].disableKeyAppend)return a;var c={};Object.keys(a).forEach(function(d){c[d+"_"+b]=a[d]});return c}
h.onNetworkFailure=function(a,b){z().info("amp-ad-network-doubleclick-impl","network error, attempt adding of error parameter",a);a=(new RegExp("[?|&]("+encodeURIComponent(T.name)+"="+(encodeURIComponent(String(T.value))+"|aet=[^&]*)$"))).test(b)?void 0:b+"&aet=n";return{adUrl:a}};
h.extractSize=function(a){var b=this.L,c=Object(null);c["qqid.AD_SLOT_ID"]=a.get("X-QQID");c["rm.AD_SLOT_ID"]=a.get("X-AmpAdRender");b.setPingParameters(c);this.U=Db(a);this.ia=a.get("X-QQID");this.G.creativeId=a.get("google-creative-id");this.G.lineItemId=a.get("google-lineitem-id");this.U&&this.fb.installExtensionForDoc(this.getAmpDoc(),"amp-analytics");this.o?this.W=a.get("X-AmpImps"):(this.fireDelayedImpressions(a.get("X-AmpImps")),this.fireDelayedImpressions(a.get("X-AmpRSImps"),!0));(a=W.prototype.extractSize.call(this,
a))?(this.ya=a,te(this,a.width,a.height)):a=this.getSlotSize();return a};h.getSlotSize=function(){var a=Number(this.element.getAttribute("width")),b=Number(this.element.getAttribute("height"));return a&&b?{width:a,height:b}:this.getIntersectionElementLayoutBox()};h.emitLifecycleEvent=function(a,b){b&&this.L.setPingParameters(b);this.L.sendPing(a)};
h.tearDownSlot=function(){W.prototype.tearDownSlot.call(this);this.element.setAttribute("data-amp-slot-index",this.win.ampAdSlotIdCounter++);this.L=this.initLifecycleReporter();if(this.qa){var a=this.qa;a.parentElement&&a.parentElement.removeChild(a);this.qa=null}this.ga=this.h=this.U=null;this.wa=!1;he=this.ya=this.Z=null;this.sraDeferred=new I;this.consentState=this.ia=null};
h.renderNonAmpCreative=function(){var a=this;if(this.postAdResponseExperimentFeatures["render-idle-throttle"]&&this.wa){if(this.win["3pla"])return(zc||Promise.resolve()).then(function(){return W.prototype.renderNonAmpCreative.call(a)});Bc(this.win);return W.prototype.renderNonAmpCreative.call(this,!0)}return W.prototype.renderNonAmpCreative.call(this)};
h.unlayoutCallback=function(){switch(this.postAdResponseExperimentFeatures.unlayout_exp){case "all":this.ga=!1;break;case "remain":if(this.ia&&null===this.ga)return z().info("amp-ad-network-doubleclick-impl","unlayoutCallback - unrendered creative can remain"),!1}this.ja&&this.ja.unobserve();if(!this.useSra&&this.ga)return!1;this.I&&(this.I.destroy(),this.I=null);return W.prototype.unlayoutCallback.call(this)};h.cleanupAfterTest=function(){this.I&&(this.I.destroy(),this.I=null)};
h.refresh=function(a){this.Va++;return W.prototype.refresh.call(this,a)};
h.initLifecycleReporter=function(){var a;a=this.element.getAttribute("data-amp-slot-index");var b=this.win;Ea(b,yd);if(mb(this)&&(H(b,"expDoubleclickA4A")||H(b,"expAdsenseA4A"))){var c=this.win,d=ub(c);c.ampAnalyticsPageLoadMetricsConfig=c.ampAnalyticsPageLoadMetricsConfig||A({requests:{fvt:"https://csi.gstatic.com/csi?s=a4a"+("&c="+d+"&met.a4a=")+"makeBodyVisible.${makeBodyVisible}~firstVisibleTime.${firstVisibleTime}~firstContentfulPaint.${firstContentfulPaint}~firstViewportReady.${firstViewportReady}"},transport:{beacon:!1,
xhrpost:!1},triggers:{iniLoad:{on:"visible",request:"fvt",selector:"body"}}});c.ampAnalyticsPageLoadMetricsElement=c.ampAnalyticsPageLoadMetricsElement||tc(this.element,c.ampAnalyticsPageLoadMetricsConfig);a=new Y(b,this.element,Number(a))}else a=new xd;a.setPingParameters({s:"AD_SLOT_NAMESPACE",dt:"NAV_TIMING(navigationStart)",v:"2",c:"AD_PAGE_CORRELATOR",rls:"AMP_VERSION",v_h:"VIEWPORT_HEIGHT",s_t:"SCROLL_TOP",slotId:"AD_SLOT_ID",stageName:"AD_SLOT_EVENT_NAME",stageIdx:"AD_SLOT_EVENT_ID","met.AD_SLOT_NAMESPACE.AD_SLOT_ID":"AD_SLOT_EVENT_NAME.AD_SLOT_TIME_TO_EVENT",
"e.AD_SLOT_ID":this.element.getAttribute("data-experiment-id"),"adt.AD_SLOT_ID":this.element.getAttribute("type"),"met.AD_SLOT_NAMESPACE":"firstVisibleTime.AD_PAGE_FIRST_VISIBLE_TIME,lastVisibleTime.AD_PAGE_LAST_VISIBLE_TIME"});return a};
h.onCreativeRender=function(a){var b=this;W.prototype.onCreativeRender.call(this,a);this.ga=!!a;a&&!a.customElementExtensions.includes("amp-ad-exit")&&Yd(this.getAmpDoc(),this.iframe.contentWindow);this.U&&(mb(this)&&Eb(this.win,this.element,this.U,this.ia,!!a,this.L.getDeltaTime(),this.L.getInitTime()),this.qa=tc(this.element,this.U,!!this.postAdResponseExperimentFeatures.avr_disable_immediate));this.isRefreshing&&(this.ja.initiateRefreshCycle(),this.isRelayoutNeededFlag=this.isRefreshing=!1);this.L.addPingsForVisibility(this.element);
a=this.ya||this.getSlotSize();var c=this.o&&this.ya&&!(0==a.width&&0==a.height);U(this.iframe,{width:a.width+"px",height:a.height+"px",position:c?"relative":null});c&&(this.element.removeAttribute("height"),U(this.element,{width:a.width+"px"}));this.ja=this.ja||Ud(this,function(){return b.useSra?(y().warn("amp-ad-network-doubleclick-impl","Refresh not compatible with SRA."),!1):ob(b.element).filter(function(a){return a!=kb["AMP-CAROUSEL"]&&a!=kb["AMP-STICKY-AD"]}).length?(y().warn("amp-ad-network-doubleclick-impl",
"Refresh not compatible with ad-containers, except for AMP-CAROUSEL and AMP-STICKY-AD"),!1):!0});this.postTroubleshootMessage()};function pe(a,b){a=a.element;var c=Ga(a),d=a.getAttribute("data-slot")||"",e=a.getAttribute("data-multi-size")||"";return na(d+":"+b+":"+e+":"+c)}function te(a,b,c){var d=a.element.getAttribute("width"),e=a.element.getAttribute("height");(a.o&&b&&c||(b!=d||c!=e)&&b<=d&&c<=e)&&a.attemptChangeSize(c,b).catch(function(){})}
h.sendXhrRequest=function(a){var b=this;if(!this.useSra)return W.prototype.sendXhrRequest.call(this,a);this.initiateSraRequests();return this.sraDeferred.promise.then(function(c){return c||W.prototype.sendXhrRequest.call(b,a)})};
h.fireDelayedImpressions=function(a,b){var c=this;a&&a.split(",").forEach(function(a){try{F(a)?c.win.document.body.appendChild(Ya(c.win.document,"amp-pixel",A({src:a,referrerpolicy:b?"no-referrer":""}))):z().warn("amp-ad-network-doubleclick-impl","insecure impression url: "+a)}catch(e){}})};h.groupSlotsForSra=function(){return qb(this.win,this.element.getAttribute("type"))};
h.initiateSraRequests=function(){var a=this;if(!he){var b=this.verifyStillCurrent();he=this.groupSlotsForSra().then(function(c){b();Object.keys(c).forEach(function(d){var e=c[d];Promise.all(e).then(function(c){b();var e=c.filter(function(a){var b=a.hasAdPromise();b||z().info("amp-ad-network-doubleclick-impl","Ignoring instance without ad promise as likely invalid",a.element);return b});if(e.length)if(1==e.length)z().info("amp-ad-network-doubleclick-impl","single block in network "+d),e[0].sraDeferred.resolve(null);
else{var f=e.map(function(a){return a.sraDeferred.resolve}),l=Ad(function(a,c,d){b();var e=Object.keys(c);1==e.length&&w(c[e[0]])&&(c=c[e[0]],c=Object.keys(c).reduce(function(a,b){a[b.toLowerCase()]=c[b];return a},{}));c["x-ampadrender"]="safeframe";f.shift()({headers:{get:function(a){(a=c[a.toLowerCase()])&&"string"!=typeof a&&(a=JSON.stringify(a));return a},has:function(a){return!!c[a.toLowerCase()]}},arrayBuffer:function(){return Ia(function(){return"undefined"!==typeof TextEncoder?(new TextEncoder("utf-8")).encode(a):
oc(unescape(encodeURIComponent(a)))})}});d&&f.length&&z().warn("amp-ad-network-doubleclick-impl","Premature end of SRA response",f.length,m)}),m;return ue(a.win,a.getAmpDoc(),e).then(function(c){b();m=c;return M(a.win,"xhr").fetch(m,{mode:"cors",method:"GET",credentials:"include"})}).then(function(c){b();return zd(a.win,c,l)}).catch(function(b){var c=cc(b);c?e.forEach(function(a){return a.sraDeferred.reject(b)}):a.win.document.querySelector("meta[name=amp-ad-doubleclick-sra]")?(sd(b,m),a.user().error("amp-ad-network-doubleclick-impl",
"SRA request failure",b),e.forEach(function(a){a.resetAdUrl();a.attemptCollapse();a.sraDeferred.reject(b)})):e.forEach(function(a){return a.sraDeferred.resolve(null)})})}})})})}};h.getPreconnectUrls=function(){return["https://securepubads.g.doubleclick.net/"]};h.getNonAmpCreativeRenderingMethod=function(a){return this.fa||this.o?"safeframe":W.prototype.getNonAmpCreativeRenderingMethod.call(this,a)};
h.getLocationQueryParameterValue=function(a){ie=ie||q(this.win.location&&this.win.location.search||"");return ie[a]};h.getAdditionalContextMetadata=function(a){a=void 0===a?!1:a;if(this.o||a){var b=this.getCreativeSize();this.I=this.I||new ce(this,this.o,b,this.W);return this.I.getSafeframeNameAttr()}};
h.postTroubleshootMessage=function(){var a=this;return this.win.opener&&/[?|&]dfpdeb/.test(this.win.location.search)?this.G.adUrl.then(function(b){var c=a.G.slotId+"_"+a.G.slotIndex;b=A({gutData:JSON.stringify(A({events:[{timestamp:Date.now(),slotid:c,messageId:4}],slots:[{contentUrl:b||"",id:c,leafAdUnitName:a.G.slotId,domId:c,lineItemId:a.G.lineItemId,creativeId:a.G.creativeId}]})),userAgent:navigator.userAgent,referrer:a.win.location.href,messageType:"LOAD"});a.win.opener.postMessage(b,"*")}):
null};h.getA4aAnalyticsVars=function(a){var b=this.ia,c=R(this.getAmpDoc()),d=this.win,d=d.performance&&d.performance.timing&&d.performance.timing.navigationStart||0,c={correlator:ub(this.win),slotId:this.element.getAttribute("data-amp-slot-index"),viewerLastVisibleTime:c.getLastVisibleTime()-d};b&&(c.qqid=b);"ad-render-start"==a&&(c.scheduleTime=this.element.layoutScheduleTime-d);return c};
h.getA4aAnalyticsConfig=function(){return A({requests:{csi:"https://csi.gstatic.com/csi?"},transport:{xhrpost:!1},triggers:{adRequestStart:Cb("ad-request-start",{"met.a4a":"afs_lvt.${viewerLastVisibleTime}~afs.${time}"}),adResponseEnd:Cb("ad-response-end",{"met.a4a":"afe.${time}"}),adRenderStart:Cb("ad-render-start",{"met.a4a":"ast.${scheduleTime}~ars_lvt.${viewerLastVisibleTime}~ars.${time}",qqid:"${qqid}"}),adIframeLoaded:Cb("ad-iframe-loaded",{"met.a4a":"ail.${time}"})},extraUrlParams:{s:"ampad",
ctx:"2",c:"${correlator}",slotId:"${slotId}",puid:"${requestCount}~${timestamp}"}})};(function(a){a.registerElement("amp-ad-network-doubleclick-impl",ne)})(self.AMP);function rb(a){return(a=/^(?:\/)?(\d+)/.exec(a.getAttribute("data-slot")))?a[1]:""}function ue(a,b,c){var d=Date.now();return sb(a,b,d).then(function(a){var b=ve(c);return Ab(Object.assign(b,a,c[0].getPageParameters(c[0].consentState)),d)})}
function ve(a){var b={output:"ldjh",impl:"fifs"};me.forEach(function(c){return Object.assign(b,c(a))});return b}function ke(a,b){var c=a?Object.keys(a).map(function(b){return we(b,a[b])}):[];b&&c.push(we("excl_cat",b));return c.length?c.join("&"):null}function we(a,b){var c=(Array.isArray(b)?b:[b]).map(encodeURIComponent).join();return encodeURIComponent(a)+"="+c}function je(a,b){for(var c=0;c<a.length;c++){var d=b(a[c]);if(d)return d}return null};
})});
//# sourceMappingURL=amp-ad-network-doubleclick-impl-0.1.js.map

