(self.AMP=self.AMP||[]).push({n:"amp-geo",v:"1527021682973",f:(function(AMP){function f(a,b){function d(){}d.prototype=b.prototype;a.prototype=new d;a.prototype.constructor=a;for(var c in b)if(Object.defineProperties){var e=Object.getOwnPropertyDescriptor(b,c);e&&Object.defineProperty(a,c,e)}else a[c]=b[c]}function g(a,b){b=void 0===b?"":b;try{return decodeURIComponent(a)}catch(d){return b}};var k=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;function l(a){var b=Object.create(null);if(!a)return b;for(var d;d=k.exec(a);){var c=g(d[1],d[1]),e=d[2]?g(d[2],d[2]):"";b[c]=e}return b};var m="";function n(a){var b=a||self,d;if(b.AMP_MODE)d=b.AMP_MODE;else{d=b;var c=l(d.location.originalHash||d.location.hash),e=l(d.location.search);m||(m=d.AMP_CONFIG&&d.AMP_CONFIG.v?d.AMP_CONFIG.v:"011527021682973");d=b.AMP_MODE={localDev:!1,development:!("1"!=c.development&&!d.AMP_DEV_MODE),examiner:"2"==c.development,filter:c.filter,geoOverride:c["amp-geo"],minified:!0,lite:void 0!=e.amp_lite,test:!1,log:c.log,version:"1527021682973",rtvVersion:m}}return d};var p=Object.prototype.toString;self.log=self.log||{user:null,dev:null,userForEmbed:null};var q=self.log;function r(){if(!q.user)throw Error("failed to call initLogConstructor");return q.user};var t=self.AMP_CONFIG||{},x=("string"==typeof t.cdnProxyRegex?new RegExp(t.cdnProxyRegex):t.cdnProxyRegex)||/^https:\/\/([a-zA-Z0-9_-]+\.)?cdn\.ampproject\.org$/;function y(a){this.m=a;this.h=Object.create(null)}y.prototype.get=function(a){if(this.h[a])return this.h[a].access=Date.now(),this.h[a].payload};y.prototype.put=function(a,b){var d=this;this.h[a]={payload:b,access:Date.now()};var c=Object.keys(this.h);if(c.length>this.m){if(q.dev)a=q.dev;else throw Error("failed to call initLogConstructor");a.warn("lru-cache","Trimming template cache");c.sort(function(a,b){return d.h[b].access-d.h[a].access});delete this.h[c[c.length-1]]}};var z,A;function B(){var a,b;this.promise=new Promise(function(d,c){a=d;b=c});this.resolve=a;this.reject=b};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
function C(a,b,d){if(b(a))d();else{var c=a.ownerDocument.defaultView;if(c.MutationObserver){var e=new c.MutationObserver(function(){b(a)&&(e.disconnect(),d())});e.observe(a,{childList:!0})}else var h=c.setInterval(function(){b(a)&&(c.clearInterval(h),d())},5)}}function D(a,b){C(a.documentElement,function(){return!!a.body},b)}function E(a){return new Promise(function(b){D(a,b)})}function F(a){return"SCRIPT"==a.tagName&&"APPLICATION/JSON"==a.getAttribute("type").toUpperCase()};var G=/amp-iso-country-(\w+)/;function H(a){a=AMP.BaseElement.call(this,a)||this;a.l=0;a.c="unknown";a.j=[];return a}f(H,AMP.BaseElement);H.prototype.buildCallback=function(){var a=this.element.children;a.length&&r().assert(1===a.length&&F(a[0]),'amp-geo can only have one <script type="application/json"> child');var b=I(this,a.length?JSON.parse(a[0].textContent):{});J.resolve(b)};
function K(a,b){var d=b.body.className.match(G),c;if(c=d){b=b.location;if("string"==typeof b)if(z||(z=self.document.createElement("a"),A=self.UrlCache||(self.UrlCache=new y(100))),c=A.get(b))b=c;else{c=z;c.href=b;c.protocol||(c.href=c.href);var e={href:c.href,protocol:c.protocol,host:c.host,hostname:c.hostname,port:"0"==c.port?"":c.port,pathname:c.pathname,search:c.search,hash:c.hash,origin:null};"/"!==e.pathname[0]&&(e.pathname="/"+e.pathname);if("http:"==e.protocol&&80==e.port||"https:"==e.protocol&&
443==e.port)e.port="",e.host=e.hostname;e.origin=c.origin&&"null"!=c.origin?c.origin:"data:"!=e.protocol&&e.host?e.protocol+"//"+e.host:e.href;A.put(b,e);b=e}c=!x.test(b.origin)}c?(a.l=1,a.c=d[1]):(a.l=0,a.c="es                          ".trim(),2!==a.c.length&&(a.c="unknown"));if(b=n(a.win).geoOverride)b=a.win,b=!(!b.AMP_CONFIG||!b.AMP_CONFIG.canary);b&&/^\w+$/.test(n(a.win).geoOverride)&&(a.l=2,a.c=n(a.win).geoOverride)}
function L(a,b){var d=b.ISOCountryGroups,c="<amp-geo> ISOCountryGroups";d&&(r().assert("[object Object]"===p.call(d),c+" must be an object"),Object.keys(d).forEach(function(b){r().assert(/^[a-z]+[a-z0-9]*$/i.test(b)&&!/^amp/.test(b),c+"["+b+"] name is invalid");r().assert(Array.isArray(d[b]),c+"["+b+"] must be an array");d[b].includes(a.c)&&a.j.push(b)}))}function M(a){var b=a.body.classList,d=[],c=/^amp-iso-country-|^amp-geo-group-/i;for(a=b.length-1;0<a;a--)c.test(b[a])&&d.push(b[a]);return d}
function I(a,b){var d=a.win.document,c={};return E(d).then(function(){K(a,d);L(a,b);var e=[];switch(a.l){case 2:e=M(d);case 0:c.ISOCountry=a.c;var h=a.j.map(function(a){c[a]=!0;return"amp-geo-group-"+a});c.ISOCountryGroups=a.j;h.push("amp-iso-country-"+a.c);a.mutateElement(function(){var a=d.body.classList;e.push("amp-geo-pending");e.forEach(function(b){return a.remove(b)});h.forEach(function(b){return a.add(b)});if(b.AmpBind){var u=d.getElementById("ampGeo");u&&u.parentNode.removeChild(u);var v=
d.createElement("amp-state"),w=d.createElement("script");w.setAttribute("type","application/json");w.textContent=JSON.stringify(c);v.appendChild(w);v.id="ampGeo";d.body.appendChild(v)}},d.body)}return{ISOCountry:a.c,ISOCountryGroups:a.j}})}var J=null;(function(a){J=new B;a.registerElement("amp-geo",H);a.registerServiceForDoc("geo",function(){return J.promise})})(self.AMP);
})});
//# sourceMappingURL=amp-geo-0.1.js.map

