(self.AMP=self.AMP||[]).push({n:"amp-accordion",v:"1527021682973",f:(function(AMP){function g(a,b){function c(){}c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a;for(var d in b)if(Object.defineProperties){var e=Object.getOwnPropertyDescriptor(b,d);e&&Object.defineProperty(a,d,e)}else a[d]=b[d]};self.log=self.log||{user:null,dev:null,userForEmbed:null};var h=self.log;function k(){if(!h.user)throw Error("failed to call initLogConstructor");return h.user};function l(a){if(a.nodeType){var b=(a.ownerDocument||a).defaultView;if(b=b!=(b.__AMP_TOP||b)&&n(b,"action")?p(b,"action"):null)return b}b=q(a);b=q(b);b=b.isSingleDoc()?b.win:b;return p(b,"action")}function q(a){if(a.nodeType){var b=(a.ownerDocument||a).defaultView,b=b.__AMP_TOP||b;a=p(b,"ampdoc").getAmpDoc(a)}return a}
function p(a,b){n(a,b);var c=a.services;c||(c=a.services={});var d=c;a=d[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj}function n(a,b){a=a.services&&a.services[b];return!(!a||!a.ctor&&!a.obj)};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
function r(a,b,c){for(var d=a;d&&d!==c;d=d.parentElement)if(b(d))return d;return null};function t(a){a=AMP.BaseElement.call(this,a)||this;a.j=[];a.l=null;a.h=null;a.m=!1;a.c=null;a.o=null;return a}g(t,AMP.BaseElement);t.prototype.isLayoutSupported=function(a){return"container"==a};
t.prototype.buildCallback=function(){var a=this;this.o=l(this.element);this.m=this.element.hasAttribute("disable-session-states");this.l=u(this);this.h=v(this);this.c=this.getRealChildren();this.c.forEach(function(b,c){k().assert("section"==b.tagName.toLowerCase(),"Sections should be enclosed in a <section> tag, See https://github.com/ampproject/amphtml/blob/master/extensions/amp-accordion/amp-accordion.md. Found in: %s",a.element);var d=b.children;k().assert(2==d.length,"Each section must have exactly two children. See https://github.com/ampproject/amphtml/blob/master/extensions/amp-accordion/amp-accordion.md. Found in: %s",
a.element);var e=d[1];e.classList.add("i-amphtml-accordion-content");var f=e.getAttribute("id");f||(f=a.element.id+"_AMP_content_"+c,e.setAttribute("id",f));a.registerAction("toggle",function(b){if(b.args){var c=b.args.section,d=a.getAmpDoc().getElementById(c);k().assertElement(d,"No element found with id:"+c);w(a,d)}else for(var m=0;m<a.c.length;m++)w(a,a.c[m])});a.registerAction("expand",function(b){if(b.args){b=b.args.section;var c=a.getAmpDoc().getElementById(b);k().assertElement(c,"No element found with id:"+
b);w(a,c,!0)}else for(b=0;b<a.c.length;b++)w(a,a.c[b],!0)});a.registerAction("collapse",function(b){if(b.args){b=b.args.section;var c=a.getAmpDoc().getElementById(b);k().assertElement(c,"No element found with id:"+b);w(a,c,!1)}else for(b=0;b<a.c.length;b++)w(a,a.c[b],!1)});a.h[f]?b.setAttribute("expanded",""):!1===a.h[f]&&b.removeAttribute("expanded");a.mutateElement(function(){});c=d[0];c.classList.add("i-amphtml-accordion-header");c.setAttribute("role","button");c.setAttribute("aria-controls",f);
c.setAttribute("aria-expanded",b.hasAttribute("expanded").toString());c.hasAttribute("tabindex")||c.setAttribute("tabindex",0);a.j.push(c);c.addEventListener("click",a.w.bind(a));c.addEventListener("keydown",a.A.bind(a))})};function u(a){var b=a.element.id||a.element.getResourceId();a=a.win.location.href;var c=a.indexOf("#");a=-1==c?a:a.substring(0,c);return"amp-"+b+"-"+a}function v(a){if(a.m)return{};try{var b=a.win.sessionStorage.getItem(a.l);return b?JSON.parse(b):{}}catch(c){return{}}}
function x(a){if(!a.m){var b=JSON.stringify(a.h);try{a.win.sessionStorage.setItem(a.l,b)}catch(c){}}}
function w(a,b,c){var d=b.children,e=d[0],d=d[1].getAttribute("id"),f=b.hasAttribute("expanded");a.mutateElement(function(){var d;(d=!0===c?!0:!1===c?!1:!b.hasAttribute("expanded"))?(b.setAttribute("expanded",""),e.setAttribute("aria-expanded","true"),a.element.hasAttribute("expand-single-section")&&a.c.forEach(function(a){a!=b&&(a.removeAttribute("expanded"),a.children[0].setAttribute("aria-expanded","false"))})):(b.removeAttribute("expanded"),e.setAttribute("aria-expanded","false"))},b);a.h[d]=
!f;x(a)}t.prototype.w=function(a){y(this,a)&&(a.preventDefault(),w(this,a.currentTarget.parentElement))};function y(a,b){var c=b.target;b=b.currentTarget;var d=!!r(c,function(a){return"A"==a.tagName},b),e=a.o.hasAction(c,"tap",b);return!d&&!e}
t.prototype.A=function(a){if(!a.defaultPrevented){var b=a.keyCode;switch(b){case 38:case 40:var c=this.j.indexOf(a.currentTarget);if(-1!==c){a.preventDefault();a=(c+(38==a.keyCode?-1:1))%this.j.length;0>a&&(a+=this.j.length);try{this.j[a].focus()}catch(d){}}break;case 13:case 32:a.target==a.currentTarget&&(a.preventDefault(),w(this,a.currentTarget.parentElement))}}};(function(a){a.registerElement("amp-accordion",t)})(self.AMP);
})});
//# sourceMappingURL=amp-accordion-0.1.js.map

