(self.AMP=self.AMP||[]).push({n:"amp-consent",v:"1527021682973",f:(function(AMP){var h;function k(a,b){function c(){}c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a;for(var d in b)if(Object.defineProperties){var e=Object.getOwnPropertyDescriptor(b,d);e&&Object.defineProperty(a,d,e)}else a[d]=b[d]}function n(a,b){b=void 0===b?"":b;try{return decodeURIComponent(a)}catch(c){return b}};var p=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;var q=Object.prototype.toString;function r(a){return"number"===typeof a&&isFinite(a)}function aa(a){var b=ba,c;for(c in b)if(b[c]===a)return!0;return!1};self.log=self.log||{user:null,dev:null,userForEmbed:null};var t=self.log;function u(){if(!t.user)throw Error("failed to call initLogConstructor");return t.user}function v(){if(t.dev)return t.dev;throw Error("failed to call initLogConstructor");};var ca=Object.prototype.hasOwnProperty;function w(){var a,b=Object.create(null);a&&Object.assign(b,a);return b};function x(a){this.fa=a;this.o=Object.create(null)}x.prototype.get=function(a){if(this.o[a])return this.o[a].access=Date.now(),this.o[a].payload};x.prototype.put=function(a,b){var c=this;this.o[a]={payload:b,access:Date.now()};var d=Object.keys(this.o);d.length>this.fa&&(v().warn("lru-cache","Trimming template cache"),d.sort(function(a,b){return c.o[b].access-c.o[a].access}),delete this.o[d[d.length-1]])};var y,z;
function da(a){if("string"==typeof a){y||(y=self.document.createElement("a"),z=self.UrlCache||(self.UrlCache=new x(100)));var b=z.get(a);if(b)a=b;else{b=y;b.href=a;b.protocol||(b.href=b.href);var c={href:b.href,protocol:b.protocol,host:b.host,hostname:b.hostname,port:"0"==b.port?"":b.port,pathname:b.pathname,search:b.search,hash:b.hash,origin:null};"/"!==c.pathname[0]&&(c.pathname="/"+c.pathname);if("http:"==c.protocol&&80==c.port||"https:"==c.protocol&&443==c.port)c.port="",c.host=c.hostname;c.origin=
b.origin&&"null"!=b.origin?b.origin:"data:"!=c.protocol&&c.host?c.protocol+"//"+c.host:c.href;z.put(a,c);a=c}}(b="https:"==a.protocol||"localhost"==a.hostname)||(a=a.hostname,b=a.length-10,b=0<=b&&a.indexOf(".localhost",b)==b);return b}
function ea(a,b){var c;c=void 0===c?"source":c;u().assert(null!=a,"%s %s must be available",b,c);var d=a;u().assert(da(d)||/^(\/\/)/.test(d),'%s %s must start with "https://" or "//" or be relative and served from either https or from localhost. Invalid value: %s',b,c,d)};function A(a,b){var c;if(a.__AMP__EXPERIMENT_TOGGLES)c=a.__AMP__EXPERIMENT_TOGGLES;else{a.__AMP__EXPERIMENT_TOGGLES=Object.create(null);c=a.__AMP__EXPERIMENT_TOGGLES;if(a.AMP_CONFIG)for(var d in a.AMP_CONFIG){var e=a.AMP_CONFIG[d];"number"===typeof e&&0<=e&&1>=e&&(c[d]=Math.random()<e)}if(a.AMP_CONFIG&&Array.isArray(a.AMP_CONFIG["allow-doc-opt-in"])&&0<a.AMP_CONFIG["allow-doc-opt-in"].length&&(d=a.AMP_CONFIG["allow-doc-opt-in"],e=a.document.head.querySelector('meta[name="amp-experiments-opt-in"]')))for(var e=
e.getAttribute("content").split(","),f=0;f<e.length;f++)-1!=d.indexOf(e[f])&&(c[e[f]]=!0);Object.assign(c,fa(a));if(a.AMP_CONFIG&&Array.isArray(a.AMP_CONFIG["allow-url-opt-in"])&&0<a.AMP_CONFIG["allow-url-opt-in"].length){d=a.AMP_CONFIG["allow-url-opt-in"];e=a.location.originalHash||a.location.hash;a=Object.create(null);if(e)for(var g;g=p.exec(e);)f=n(g[1],g[1]),g=g[2]?n(g[2],g[2]):"",a[f]=g;for(e=0;e<d.length;e++)f=a["e-"+d[e]],"1"==f&&(c[d[e]]=!0),"0"==f&&(c[d[e]]=!1)}}var l=c;return!!l[b]}
function fa(a){a:{var b;try{b=a.document.cookie}catch(l){b=""}if(a=b)for(a=a.split(";"),b=0;b<a.length;b++){var c=a[b].trim(),d=c.indexOf("="),e;if(e=-1!=d)e=c.substring(0,d).trim(),e="AMP_EXP"==n(e,void 0);if(e){a=c.substring(d+1).trim();a=n(a,a);break a}}a=null}var f=a,g=f?f.split(/\s*,\s*/g):[];a=Object.create(null);for(b=0;b<g.length;b++)0!=g[b].length&&("-"==g[b][0]?a[g[b].substr(1)]=!1:a[g[b]]=!0);return a};function B(){var a,b;this.promise=new Promise(function(c,d){a=c;b=d});this.resolve=a;this.reject=b};function C(a,b){a=a.__AMP_TOP||a;return D(a,b)}function ga(a){a=E(a);a=F(a);return D(a,"viewer")}function G(a,b){a=F(a);var c=H(a,b);if(!c){var d=new B,c=d.promise,d=d.resolve;I(a)[b]={obj:null,promise:c,resolve:d,context:null,ctor:null}}b=c;return b}function E(a){return a.nodeType?C((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}function F(a){a=E(a);return a.isSingleDoc()?a.win:a}
function D(a,b){var c=I(a);a=c[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj}function H(a,b){var c=I(a)[b];if(c){if(c.promise)return c.promise;D(a,b);return c.promise=Promise.resolve(c.obj)}return null}function I(a){var b=a.services;b||(b=a.services={});return b};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
function ha(a,b,c){if(b(a))c();else{var d=a.ownerDocument.defaultView;if(d.MutationObserver){var e=new d.MutationObserver(function(){b(a)&&(e.disconnect(),c())});e.observe(a,{childList:!0})}else var f=d.setInterval(function(){b(a)&&(d.clearInterval(f),c())},5)}}function ia(a,b){ha(a.documentElement,function(){return!!a.body},b)}function ja(a){return new Promise(function(b){ia(a,b)})}var J;function ka(a){return"SCRIPT"==a.tagName&&"APPLICATION/JSON"==a.getAttribute("type").toUpperCase()};var la=[];function ma(a){var b=H(a,"geo");return b?b:na(a)}function na(a){return ja(a.document).then(function(){var b;b=la.includes("amp-geo")?C(a,"extensions").waitForExtension(a,"amp-geo"):Promise.resolve();return b}).then(function(){return H(a,"geo")})};var L,M="Webkit webkit Moz moz ms O o".split(" ");function N(a,b,c){if(2>b.length?0:0==b.lastIndexOf("--",0))return b;L||(L=w());var d=L[b];if(!d||c){d=b;if(void 0===a[b]){var e=b.charAt(0).toUpperCase()+b.slice(1);a:{for(var f=0;f<M.length;f++){var g=M[f]+e;if(void 0!==a[g]){e=g;break a}}e=""}var l=e;void 0!==a[l]&&(d=l)}c||(L[b]=d)}return d}function O(a){var b={display:"block"},c;for(c in b)a.style.setProperty(N(b,c),b[c].toString(),"important")}
function P(a,b){if(void 0===b){var c;c=(c=N(a.style,"display",void 0))?a.style[c]:void 0;b="none"==c}c=b?"":"none";var d=N(a.style,"display",void 0);d&&(a.style[d]=c)};function Q(){this.l=null}h=Q.prototype;h.add=function(a){var b=this;this.l||(this.l=[]);this.l.push(a);return function(){b.remove(a)}};h.remove=function(a){this.l&&(a=this.l.indexOf(a),-1<a&&this.l.splice(a,1))};h.removeAll=function(){this.l&&(this.l.length=0)};h.fire=function(a){if(this.l)for(var b=this.l,c=0;c<b.length;c++)(0,b[c])(a)};h.getHandlerCount=function(){return this.l?this.l.length:0};function R(){this.C=0;this.aa=Promise.resolve();this.Z=function(){};this.$=function(){}}R.prototype.onQueueEmpty=function(a){this.Z=a;0==this.C&&a()};R.prototype.onQueueNotEmpty=function(a){this.$=a;0<this.C&&a()};R.prototype.registerUI=function(a){var b=this;0==this.C&&this.$();this.C++;var c=this.aa.then(function(){return a().then(function(){b.C--;0==b.C&&b.Z()})});return this.aa=c};var ba={UNKNOWN:0,GRANTED:1,REJECTED:2,DISMISSED:3,NOT_REQUIRED:4};function S(a){this.D=a;this.m={};this.R={};this.H={};this.G={}}h=S.prototype;h.registerConsentInstance=function(a){this.m[a]=new T(this.D,a);this.R[a]=new Q;this.H[a]&&(this.H[a](),this.G[a]=null,this.H[a]=null)};h.updateConsentInstanceState=function(a,b){this.R[a].fire(b);this.m[a].update(b)};h.getConsentInstanceState=function(a){return this.m[a].get()};
h.onConsentStateChange=function(a,b){var c=this.R[a].add(b);this.getConsentInstanceState(a).then(function(a){b(a)});return c};h.setConsentInstanceSharedData=function(a,b){this.m[a].sharedDataPromise=b};h.getConsentInstanceSharedData=function(a){return this.m[a].sharedDataPromise};h.whenConsentReady=function(a){if(this.m[a])return Promise.resolve();if(!this.G[a]){var b=new B;this.G[a]=b.promise;this.H[a]=b.resolve}return this.G[a]};
function T(a,b){this.sharedDataPromise=null;this.da=G(a,"storage");this.h=null;this.ca="amp-consent:"+b}T.prototype.update=function(a){var b=this;aa(a)||(a=0);if(3==a)this.h=this.h||0;else if(4==a)this.h&&0!=this.h||(this.h=4);else if(a!==this.h&&(this.h=a,0!=a)){var c=1==a;this.da.then(function(d){a==b.h&&d.set(b.ca,c)})}};
T.prototype.get=function(){var a=this;return this.h?Promise.resolve(this.h):this.da.then(function(b){return b.get(a.ca)}).then(function(b){if(a.h)return a.h;a.h=void 0===b?0:b?1:2;return a.h}).catch(function(a){v().error("CONSENT-STATE-MANAGER","Failed to read storage",a);return 0})};function U(a){this.D=a;this.M=w();this.L=w();this.m=w();this.X=G(this.D,"consentStateManager");a=new B;this.ea=a.promise;this.P=a.resolve}
U.prototype.registerConsentPolicyInstance=function(a,b){var c=this,d=Object.keys(b.waitFor||{}),e=new V(b);this.m[a]=e;this.L[a]&&(this.L[a](),this.L[a]=null,this.M[a]=null);var f=[];this.X.then(function(a){for(var b={},g=0;g<d.length;b={consentId:b.consentId,resolver:b.resolver},g++){b.consentId=d[g];var K=new B,oa=K.promise;b.resolver=K.resolve;a.whenConsentReady(b.consentId).then(function(b){return function(){a.onConsentStateChange(b.consentId,function(a){b.resolver&&(b.resolver(),b.resolver=null);
e.consentStateChangeHandler(b.consentId,a)})}}(b));f.push(oa)}c.ea.then(function(){Promise.all(f).then(function(){e.startTimeout(c.D.win)})})})};U.prototype.enableTimeout=function(){this.P&&this.P();this.P=null};
U.prototype.whenPolicyResolved=function(a){var b=this;return A(this.D.win,"multi-consent")||"default"==a?pa(this,a).then(function(){return b.m[a].getReadyPromise().then(function(){return b.m[a].getCurrentPolicyStatus()})}):(u().error("consent-policy-manager","can not find policy, do not set value to data-block-on-consent"),Promise.resolve(0))};
U.prototype.getMergedSharedData=function(a){var b=this;return this.whenPolicyResolved(a).then(function(){return b.X}).then(function(c){var d=b.m[a].getConsentInstanceIds().map(function(a){return c.getConsentInstanceSharedData(a)});return Promise.all(d)}).then(function(a){a.unshift({});return Object.assign.apply(null,a)})};function pa(a,b){if(a.m[b])return Promise.resolve();if(!a.M[b]){var c=new B;a.M[b]=c.promise;a.L[b]=c.resolve}return a.M[b]}
function V(a){var b=Object.keys(a.waitFor||{});this.ga=a;this.c=w();a=new B;this.ha=a.promise;this.W=a.resolve;this.ba=0;this.U(b)}h=V.prototype;h.U=function(a){for(var b=0;b<a.length;b++)this.c[a[b]]=null};h.getConsentInstanceIds=function(){return Object.keys(this.c)};
h.startTimeout=function(a){var b=this,c=this.ga.timeout,d=null,e;void 0!=c&&("[object Object]"===q.call(c)?(c.fallbackAction&&"reject"==c.fallbackAction?e=2:c.fallbackAction&&"dismiss"!=c.fallbackAction&&u().error("consent-policy-manager","unsupported fallbackAction "+c.fallbackAction),d=c.seconds):d=c,u().assert(r(d),"invalid timeout value "+d));null!=d&&a.setTimeout(function(){W(b,!0,e)},1E3*d)};
h.consentStateChangeHandler=function(a,b){ca.call(this.c,a);if(0!=b){if(4==b){var c=1!=this.c[a]&&2!=this.c[a];c&&(this.c[a]=4)}else 3==b?null===this.c[a]&&(this.c[a]=0):this.c[a]=b;W(this)}};function W(a,b,c){b=void 0===b?!1:b;for(var d=!0,e=!0,f=!1,g=Object.keys(a.c),l=0;l<g.length;l++){var m=g[l];if(null===a.c[m])if(b)a.c[m]=c||0;else return;4==a.c[m]&&(d=!1);2==a.c[m]&&(e=d=!1);0==a.c[m]&&(e=d=!1,f=!0)}a.ba=d?1:e?3:f?0:2;a.W&&(a.W(),a.W=null)}h.getReadyPromise=function(){return this.ha};
h.getCurrentPolicyStatus=function(){return this.ba};function X(a){a=AMP.BaseElement.call(this,a)||this;a.A=null;a.S=null;a.K=null;a.I=w();a.w={};a.B={};a.Y=w();a.N=!1;a.j=null;a.F=null;a.J=w();a.T=w();a.V=!1;a.O=a.getVsync();return a}k(X,AMP.BaseElement);X.prototype.getConsentPolicy=function(){return null};
X.prototype.buildCallback=function(){var a=this;if(A(this.win,"amp-consent")){this.V=A(this.win,"multi-consent");u().assert(this.element.getAttribute("id"),"amp-consent should have an id");qa(this);for(var b=this.getRealChildren(),c=0;c<b.length;c++)this.setAsOwner(b[c]);var d=G(this.getAmpDoc(),"consentPolicyManager").then(function(b){a.S=b;if(!a.B||!a.B["default"]){b=Object.keys(a.w);for(var c={},d=0;d<b.length;d++)c[b[d]]=void 0;a.B["default"]={waitFor:c}}var e=Object.keys(a.B);for(b=0;b<e.length;b++)a.S.registerConsentPolicyInstance(e[b],
a.B[e[b]])}),e=G(this.getAmpDoc(),"consentStateManager").then(function(b){a.A=b}),f=G(this.getAmpDoc(),"notificationUIManager").then(function(b){a.K=b});Promise.all([e,f,d]).then(function(){a.U()})}};
function ra(a){a.registerAction("accept",function(){return Y(a,0)});a.registerAction("reject",function(){return Y(a,1)});a.registerAction("dismiss",function(){return Y(a,2)});a.registerAction("prompt",function(b){var c=b.args,d=c&&c.consent;a.V||(d=Object.keys(a.w)[0]);d=d||"";u().assert(a.w[d],"consent with id "+d+" not found");Z(a,d)})}function Z(a,b){!a.T[b]&&a.I[b]&&(a.T[b]=!0,a.K.registerUI(a.ia.bind(a,b)))}
X.prototype.ia=function(a){var b=this;this.O.mutate(function(){b.N||(b.N=!0,P(b.element,!0));b.element.classList.remove("amp-hidden");b.element.classList.add("amp-active");b.getViewport().addToFixedLayer(b.element);b.j=a;var c=b.I[b.j];O(c);b.scheduleLayout(c)});var c=new B;this.J[a]=c.resolve;return c.promise};
function sa(a){var b=a.j&&a.I[a.j];a.O.mutate(function(){a.element.classList.add("amp-hidden");a.element.classList.remove("amp-active");a.getViewport().removeFromFixedLayer(a.element);P(b,!1)});a.J[a.j]&&(a.J[a.j](),a.J[a.j]=null);a.T[a.j]=!1;a.j=null}function Y(a,b){0==b?a.A.updateConsentInstanceState(a.j,1):1==b?a.A.updateConsentInstanceState(a.j,2):2==b&&a.A.updateConsentInstanceState(a.j,3);sa(a)}
X.prototype.U=function(){for(var a=this,b=Object.keys(this.w),c=[],d={},e=0;e<b.length;d={instanceId:d.instanceId},e++){d.instanceId=b[e];this.A.registerConsentInstance(d.instanceId);var f=ta(this,d.instanceId,this.w[d.instanceId]),g=f.then(function(b){return function(){return ua(a,b.instanceId)}}(d)).catch(function(){});c.push(g)}Promise.all(c).then(function(){va(a);a.S.enableTimeout()});ra(this)};
function ta(a,b,c){u().assert(c.checkConsentHref||c.promptIfUnknownForGeoGroup,"neither checkConsentHref nor promptIfUnknownForGeoGroup is defined");var d=Promise.resolve(null);c.checkConsentHref&&(d=wa(a,b),xa(a,b,d));var e=Promise.resolve();if(c.promptIfUnknownForGeoGroup)var f=c.promptIfUnknownForGeoGroup,e=ya(a,f);return e.then(function(c){return d.then(function(d){var e=a.Y,f=c;d&&1==d.promptIfUnknown?f=!0:d&&0==d.promptIfUnknown?f=!1:void 0==f&&(f=!1);e[b]=f})})}
function xa(a,b,c){var d=c.then(function(a){return a&&void 0!==a.sharedData?a.sharedData:null});a.A.setConsentInstanceSharedData(b,d)}function ya(a,b){return ma(a.win).then(function(a){u().assert(a,"requires <amp-geo> to use promptIfUnknownForGeoGroup");return 0<=a.ISOCountryGroups.indexOf(b)})}
function wa(a,b){var c={credentials:"include",method:"POST",body:{consentInstanceId:b},requireAmpResponseSourceOrigin:!1},d=a.w[b].checkConsentHref;ea(d,a.element);var e=ga(a.getAmpDoc());return e.whenFirstVisible().then(function(){return C(a.win,"xhr").fetchJson(d,c).then(function(a){return a.json()})})}
function qa(a){var b;b=a.element;if(null==J){var c=b.ownerDocument;try{var d=c.createElement("div"),e=c.createElement("div");d.appendChild(e);J=d.querySelector(":scope div")===e}catch(K){J=!1}}J?b=b.querySelectorAll(":scope > script"):(b.classList.add("i-amphtml-scoped"),c=b.querySelectorAll(".i-amphtml-scoped > script"),b.classList.remove("i-amphtml-scoped"),b=c);var f=b;u().assert(1==f.length,"amp-consent should have (only) one <script> child");var g=f[0];u().assert(ka(g),'amp-consent consent instance config should be put in a <script>tag with type= "application/json"');
b=JSON.parse(g.textContent);var l=b.consents;u().assert(l,"amp-consent: consents config is required");u().assert(0!=Object.keys(l).length,"amp-consent: can't find consent instance");if(!a.V&&(u().assert(1>=Object.keys(l).length,"amp-consent: only single consent instance is supported"),b.policy))for(var m=Object.keys(b.policy),c=0;c<m.length;c++)"default"!=m[c]&&(u().warn("amp-consent","policy "+m[c]+" is currently not supportedand will be ignored"),delete b.policy[m[c]]);a.w=l;b.postPromptUI&&(a.F=
a.getAmpDoc().getElementById(b.postPromptUI));a.B=b.policy||a.B}function ua(a,b){var c=a.w[b].promptUI,d=a.getAmpDoc().getElementById(c);a.I[b]=d;return a.A.getConsentInstanceState(b).then(function(c){0==c&&(a.Y[b]?Z(a,b):a.A.updateConsentInstanceState(b,4))})}
function va(a){var b=a.element.classList;a.K.onQueueEmpty(function(){a.F&&a.O.mutate(function(){a.N||(a.N=!0,P(a.element,!0));b.add("amp-active");b.remove("amp-hidden");a.getViewport().addToFixedLayer(a.element);O(a.F)})});a.K.onQueueNotEmpty(function(){a.F&&a.O.mutate(function(){a.j||(b.add("amp-hidden"),b.remove("amp-active"));a.getViewport().removeFromFixedLayer(a.element);P(a.F,!1)})})}
(function(a){a.registerElement("amp-consent",X,"amp-consent{position:fixed;bottom:0;left:0;overflow:hidden!important;background:hsla(0,0%,100%,0.7);z-index:1000;width:100%}amp-consent>*{display:none!important;max-height:100vh!important}amp-consent.amp-active{visibility:visible}amp-consent.amp-hidden{visibility:hidden}\n/*# sourceURL=/extensions/amp-consent/0.1/amp-consent.css*/");a.registerServiceForDoc("notificationUIManager",R);a.registerServiceForDoc("consentStateManager",S);a.registerServiceForDoc("consentPolicyManager",
U)})(self.AMP);
})});
//# sourceMappingURL=amp-consent-0.1.js.map

